export type ServiceCategory =
  | 'education'
  | 'health'
  | 'pharmacy'
  | 'shopping'
  | 'food'
  | 'finance'
  | 'security'
  | 'transport'
  | 'fuel';

export interface NearbyService {
  id: string;
  name: string;
  category: ServiceCategory;
  city: string;
  district: string;
  address: string;
  latitude: number;
  longitude: number;
  phone?: string;
  isOpen24h?: boolean;
}

export const COTE_D_IVOIRE_SERVICES: NearbyService[] = [
  // ─── ÉDUCATION (Écoles, Lycées, Universités) ──────────────────────────
  {
    id: 'edu-1',
    name: 'Université Félix Houphouët-Boigny (Cocody)',
    category: 'education',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard de l\'Université, Cocody',
    latitude: 5.3486,
    longitude: -3.9875,
  },
  {
    id: 'edu-2',
    name: 'Lycée Classique d\'Abidjan (Cocody)',
    category: 'education',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard des Martyrs, Cocody',
    latitude: 5.3522,
    longitude: -4.0044,
  },
  {
    id: 'edu-3',
    name: 'Lycée International Jean-Mermoz (Cocody)',
    category: 'education',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Avenue Jean-Mermoz, Cocody',
    latitude: 5.3370,
    longitude: -4.0080,
  },
  {
    id: 'edu-4',
    name: 'École Internationale Jules Verne (Riviera 3)',
    category: 'education',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Riviera 3, près de Cap Nord',
    latitude: 5.3735,
    longitude: -3.9680,
  },
  {
    id: 'edu-5',
    name: 'Institut National Polytechnique FHB (INP-HB)',
    category: 'education',
    city: 'Yamoussoukro',
    district: 'Morofé',
    address: 'Zone Universitaire, Yamoussoukro',
    latitude: 6.8375,
    longitude: -5.2980,
  },
  {
    id: 'edu-6',
    name: 'Lycée Technique d\'Abidjan (Cocody)',
    category: 'education',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard Latrille, Cocody',
    latitude: 5.3440,
    longitude: -4.0095,
  },
  {
    id: 'edu-7',
    name: 'Groupe Scolaire Les Papillons (Marcory Zone 4)',
    category: 'education',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Rue du Docteur Blanchard, Zone 4C',
    latitude: 5.2890,
    longitude: -3.9780,
  },
  {
    id: 'edu-8',
    name: 'Lycée Municipal de Yopougon (Niangon)',
    category: 'education',
    city: 'Abidjan',
    district: 'Yopougon',
    address: 'Niangon Sud à Droite, Yopougon',
    latitude: 5.3350,
    longitude: -4.0950,
  },

  // ─── SANTÉ (Hôpitaux & Cliniques) ────────────────────────────────────
  {
    id: 'health-1',
    name: 'Polyclinique Sainte Anne-Marie (PISAM)',
    category: 'health',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Rue Cannebière, Cocody Ambassades',
    latitude: 5.3385,
    longitude: -4.0010,
    isOpen24h: true,
    phone: '+225 27 22 48 31 31',
  },
  {
    id: 'health-2',
    name: 'CHU de Cocody (Hôpital Universitaire)',
    category: 'health',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard de l\'Université, Cocody',
    latitude: 5.3495,
    longitude: -3.9905,
    isOpen24h: true,
  },
  {
    id: 'health-3',
    name: 'CHU d\'Angré (Nouveau CHU)',
    category: 'health',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard Mitterrand Prolongé, Angré',
    latitude: 5.4120,
    longitude: -3.9750,
    isOpen24h: true,
  },
  {
    id: 'health-4',
    name: 'Polyclinique Internationale de l\'Indénié (Plateau)',
    category: 'health',
    city: 'Abidjan',
    district: 'Plateau',
    address: 'Boulevard de l\'Indénié, Plateau',
    latitude: 5.3325,
    longitude: -4.0180,
    isOpen24h: true,
  },
  {
    id: 'health-5',
    name: 'Polyclinique Avicennes (Marcory Zone 4)',
    category: 'health',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Rue Paul Langevin, Zone 4C',
    latitude: 5.2910,
    longitude: -3.9740,
    isOpen24h: true,
  },
  {
    id: 'health-6',
    name: 'CHU de Yopougon',
    category: 'health',
    city: 'Abidjan',
    district: 'Yopougon',
    address: 'Route de Dabou, Yopougon',
    latitude: 5.3460,
    longitude: -4.0750,
    isOpen24h: true,
  },
  {
    id: 'health-7',
    name: 'Hôpital Général de Grand-Bassam',
    category: 'health',
    city: 'Grand-Bassam',
    district: 'Grand-Bassam',
    address: 'Quartier Impérial, Grand-Bassam',
    latitude: 5.2110,
    longitude: -3.7420,
    isOpen24h: true,
  },

  // ─── PHARMACIES ───────────────────────────────────────────────────────
  {
    id: 'pharma-1',
    name: 'Grande Pharmacie de la Riviera 3',
    category: 'pharmacy',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Carrefour Riviera 3, Cocody',
    latitude: 5.3720,
    longitude: -3.9695,
    isOpen24h: true,
  },
  {
    id: 'pharma-2',
    name: 'Pharmacie Sainte Cécile (2 Plateaux)',
    category: 'pharmacy',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Rue des Jardins, 2 Plateaux Vallon',
    latitude: 5.3620,
    longitude: -4.0090,
    isOpen24h: true,
  },
  {
    id: 'pharma-3',
    name: 'Pharmacie du Plateau (Nour-Al-Hayat)',
    category: 'pharmacy',
    city: 'Abidjan',
    district: 'Plateau',
    address: 'Avenue Chardy, Plateau',
    latitude: 5.3260,
    longitude: -4.0140,
    isOpen24h: true,
  },
  {
    id: 'pharma-4',
    name: 'Pharmacie du Canal (Zone 4C)',
    category: 'pharmacy',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Boulevard de Marseille, Zone 4',
    latitude: 5.2860,
    longitude: -3.9810,
    isOpen24h: true,
  },
  {
    id: 'pharma-5',
    name: 'Pharmacie Bel Air (Yopougon)',
    category: 'pharmacy',
    city: 'Abidjan',
    district: 'Yopougon',
    address: 'Carrefour Bel Air, Yopougon',
    latitude: 5.3420,
    longitude: -4.0830,
    isOpen24h: true,
  },

  // ─── COMMERCE & SUPERMARCHÉS ─────────────────────────────────────────
  {
    id: 'shop-1',
    name: 'Centre Commercial Cap Sud / Hyper U (Marcory)',
    category: 'shopping',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Boulevard Valéry Giscard d\'Estaing, Marcory',
    latitude: 5.2980,
    longitude: -3.9870,
  },
  {
    id: 'shop-2',
    name: 'Playce Marcory & Hypermarché Carrefour',
    category: 'shopping',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Boulevard VGE, Marcory',
    latitude: 5.2950,
    longitude: -3.9840,
  },
  {
    id: 'shop-3',
    name: 'Cap Nord / Casino Supermarché (Riviera 3)',
    category: 'shopping',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard Mitterrand, Riviera 3',
    latitude: 5.3750,
    longitude: -3.9660,
  },
  {
    id: 'shop-4',
    name: 'Sococé 2 Plateaux (Centre Commercial)',
    category: 'shopping',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard Latrille, 2 Plateaux',
    latitude: 5.3580,
    longitude: -4.0040,
  },
  {
    id: 'shop-5',
    name: 'Playce Palmeraie / Carrefour Market',
    category: 'shopping',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Riviera Palmeraie, Cocody',
    latitude: 5.3890,
    longitude: -3.9450,
  },
  {
    id: 'shop-6',
    name: 'Marché Traditionnel de Cocody',
    category: 'shopping',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Avenue Jean-Mermoz, Cocody Centre',
    latitude: 5.3410,
    longitude: -4.0120,
  },
  {
    id: 'shop-7',
    name: 'Prima Center (Zone 4C)',
    category: 'shopping',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Rue Pierre & Marie Curie, Zone 4',
    latitude: 5.2885,
    longitude: -3.9725,
  },
  {
    id: 'shop-8',
    name: 'Cosmos Yopougon (Grand Centre Commercial)',
    category: 'shopping',
    city: 'Abidjan',
    district: 'Yopougon',
    address: 'Boulevard Principal, Yopougon Selmer',
    latitude: 5.3390,
    longitude: -4.0680,
  },

  // ─── RESTAURATION & CAFÉS ────────────────────────────────────────────
  {
    id: 'food-1',
    name: 'Le Grand Large (Biétry / Lagune)',
    category: 'food',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Boulevard de Marseille, Biétry',
    latitude: 5.2780,
    longitude: -3.9790,
  },
  {
    id: 'food-2',
    name: 'Restaurant Saakan (Plateau)',
    category: 'food',
    city: 'Abidjan',
    district: 'Plateau',
    address: 'Avenue Chardy, Plateau',
    latitude: 5.3250,
    longitude: -4.0150,
  },
  {
    id: 'food-3',
    name: 'Norima Gastronomie Américaine & Grill (2 Plateaux)',
    category: 'food',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Rue des Jardins, Vallon',
    latitude: 5.3640,
    longitude: -4.0070,
  },
  {
    id: 'food-4',
    name: 'La Croisette (Plateau)',
    category: 'food',
    city: 'Abidjan',
    district: 'Plateau',
    address: 'Rue Botreau Roussel, Plateau',
    latitude: 5.3220,
    longitude: -4.0170,
  },

  // ─── BANQUES & DAB ───────────────────────────────────────────────────
  {
    id: 'bank-1',
    name: 'Société Générale Côte d\'Ivoire (Siège Plateau)',
    category: 'finance',
    city: 'Abidjan',
    district: 'Plateau',
    address: 'Avenue Delafosse, Plateau',
    latitude: 5.3235,
    longitude: -4.0190,
    isOpen24h: true,
  },
  {
    id: 'bank-2',
    name: 'Ecobank Côte d\'Ivoire (Agence Riviera 3)',
    category: 'finance',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard Mitterrand, Riviera 3',
    latitude: 5.3715,
    longitude: -3.9710,
    isOpen24h: true,
  },
  {
    id: 'bank-3',
    name: 'BICICI BNP Paribas (Agence 2 Plateaux Vallon)',
    category: 'finance',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Rue des Jardins, 2 Plateaux',
    latitude: 5.3610,
    longitude: -4.0110,
    isOpen24h: true,
  },
  {
    id: 'bank-4',
    name: 'Bank of Africa (BOA Zone 4)',
    category: 'finance',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Rue du Docteur Blanchard, Zone 4',
    latitude: 5.2900,
    longitude: -3.9760,
    isOpen24h: true,
  },

  // ─── SÉCURITÉ (Police & Gendarmerie) ──────────────────────────────────
  {
    id: 'sec-1',
    name: 'Commissariat de Police du 8ème Arrondissement (Cocody)',
    category: 'security',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard des Martyrs, Cocody Danga',
    latitude: 5.3510,
    longitude: -4.0020,
    isOpen24h: true,
    phone: '+225 27 22 44 14 62',
  },
  {
    id: 'sec-2',
    name: 'Commissariat du 18ème Arrondissement (Riviera 3)',
    category: 'security',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Riviera 3, près du Lycée Français',
    latitude: 5.3760,
    longitude: -3.9640,
    isOpen24h: true,
  },
  {
    id: 'sec-3',
    name: 'Commissariat du 1er Arrondissement (Plateau)',
    category: 'security',
    city: 'Abidjan',
    district: 'Plateau',
    address: 'Avenue Franchet d\'Esperey, Plateau',
    latitude: 5.3210,
    longitude: -4.0160,
    isOpen24h: true,
  },
  {
    id: 'sec-4',
    name: 'Commissariat du 4ème Arrondissement (Zone 4)',
    category: 'security',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Rue Thomas Edison, Zone 4C',
    latitude: 5.2870,
    longitude: -3.9795,
    isOpen24h: true,
  },

  // ─── TRANSPORT (Bateaux-Bus, Gares & Métro) ───────────────────────────
  {
    id: 'trans-1',
    name: 'Gare Lagunaire STL / Citrans de Cocody Blockhaus',
    category: 'transport',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Lagune Ébrié, Blockhaus Cocody',
    latitude: 5.3340,
    longitude: -4.0050,
  },
  {
    id: 'trans-2',
    name: 'Gare Centrale SOTRA du Plateau',
    category: 'transport',
    city: 'Abidjan',
    district: 'Plateau',
    address: 'Boulevard Carde, Plateau',
    latitude: 5.3280,
    longitude: -4.0210,
  },
  {
    id: 'trans-3',
    name: 'Aéroport International Félix Houphouët-Boigny (ABJ)',
    category: 'transport',
    city: 'Abidjan',
    district: 'Port-Bouët',
    address: 'Boulevard de l\'Aéroport, Port-Bouët',
    latitude: 5.2614,
    longitude: -3.9263,
  },
  {
    id: 'trans-4',
    name: 'Échangeur du 3ème Pont Henri Konan Bédié (HKB)',
    category: 'transport',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Liaison Riviera - Marcory Zone 4',
    latitude: 5.3580,
    longitude: -3.9850,
  },

  // ─── STATIONS-SERVICE & ÉNERGIE ──────────────────────────────────────
  {
    id: 'fuel-1',
    name: 'Station TotalEnergies Riviera 3',
    category: 'fuel',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard Mitterrand, Riviera 3',
    latitude: 5.3740,
    longitude: -3.9670,
    isOpen24h: true,
  },
  {
    id: 'fuel-2',
    name: 'Station Shell 2 Plateaux Latrille',
    category: 'fuel',
    city: 'Abidjan',
    district: 'Cocody',
    address: 'Boulevard Latrille, 2 Plateaux',
    latitude: 5.3600,
    longitude: -4.0060,
    isOpen24h: true,
  },
  {
    id: 'fuel-3',
    name: 'Station Petroci VGE (Marcory)',
    category: 'fuel',
    city: 'Abidjan',
    district: 'Marcory',
    address: 'Boulevard VGE, Marcory',
    latitude: 5.2930,
    longitude: -3.9860,
    isOpen24h: true,
  },
];
