import { useCallback, useState, useEffect, useMemo } from 'react';
import createContextHook from '@nkzw/create-context-hook';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';

export type LanguageCode = 'en' | 'fr';

export interface TranslationEntry {
  en: string;
  fr: string;
}

export type Dictionary = Record<string, TranslationEntry>;

export const dictionary: Dictionary = {
  nav_home: { en: "Home", fr: "Accueil" },
  nav_search: { en: "Search", fr: "Recherche" },
  nav_favorites: { en: "Favorites", fr: "Favoris" },
  nav_profile: { en: "Profile", fr: "Profil" },
  nav_buy: { en: "Buy", fr: "Acheter" },
  nav_rent: { en: "Rent", fr: "Louer" },
  nav_add_property: { en: "Add Property", fr: "Ajouter un bien" },
  nav_login: { en: "Login", fr: "Connexion" },
  nav_signup: { en: "Sign Up", fr: "Inscription" },
  language_english: { en: "English", fr: "Anglais" },
  language_french: { en: "French", fr: "Français" },
  features_search_title: { en: "Search Properties", fr: "Rechercher des propriétés" },
  features_search_desc: { en: "Find your ideal property easily", fr: "Trouvez votre bien idéal facilement" },
  features_buy_title: { en: "Buy & Rent", fr: "Acheter & Louer" },
  features_buy_desc: { en: "Buy or rent with confidence", fr: "Achetez ou louez en toute confiance" },
  features_location_title: { en: "Location", fr: "Localisation" },
  features_location_desc: { en: "Explore by neighborhood", fr: "Explorez par quartier" },
  features_community_title: { en: "Community", fr: "Communauté" },
  features_community_desc: { en: "Trusted property owners", fr: "Propriétaires de confiance" },
  features_security_title: { en: "Guaranteed Security", fr: "Sécurité garantie" },
  features_security_desc: { en: "Secure and verified transactions", fr: "Transactions sécurisées et vérifiées" },
  features_quick_title: { en: "Quick Service", fr: "Service rapide" },
  features_quick_desc: { en: "Response within 24 hours", fr: "Réponse sous 24 heures" },
  settings_title: { en: "Settings", fr: "Paramètres" },
  settings_general: { en: "General", fr: "Général" },
  settings_language: { en: "Language", fr: "Langue" },
  settings_notifications: { en: "Notifications", fr: "Notifications" },
  settings_dark_mode: { en: "Dark Mode", fr: "Mode sombre" },
  settings_enabled: { en: "Enabled", fr: "Activé" },
  settings_disabled: { en: "Disabled", fr: "Désactivé" },
  favorites_title: { en: "My Favorites", fr: "Mes Favoris" },
  favorites_properties: { en: "properties", fr: "biens" },
  favorites_empty_title: { en: "No favorites", fr: "Aucun favori" },
  favorites_empty_text: { en: "Properties you like will appear here", fr: "Les biens que vous aimez apparaîtront ici" },
  profile_edit: { en: "Edit Profile", fr: "Modifier le profil" },
  profile_my_account: { en: "My Account", fr: "Mon Compte" },
  profile_my_favorites: { en: "My Favorites", fr: "Mes Favoris" },
  profile_my_listings: { en: "My Listings", fr: "Mes Annonces" },
  profile_settings: { en: "Settings", fr: "Paramètres" },
  profile_help: { en: "Help & Support", fr: "Aide & Support" },
  profile_logout: { en: "Logout", fr: "Déconnexion" },
  search_buy: { en: "Buy", fr: "Acheter" },
  search_rent: { en: "Rent", fr: "Louer" },
  search_location: { en: "Location", fr: "Localisation" },
  search_any: { en: "Any", fr: "Tous" },
  search_properties: { en: "Search Properties", fr: "Rechercher des biens" },
  search_no_results: { en: "No properties found", fr: "Aucun bien trouvé" },
  search_filters: { en: "Filters", fr: "Filtres" },
  search_property_type: { en: "Property Type", fr: "Type de bien" },
  search_status: { en: "Status", fr: "Statut" },
  search_bedrooms: { en: "Bedrooms", fr: "Chambres" },
  search_bathrooms: { en: "Bathrooms", fr: "Salles de bain" },
  search_reset: { en: "Reset", fr: "Réinitialiser" },
  search_apply: { en: "Apply", fr: "Appliquer" },
  search_all: { en: "All", fr: "Tous" },
  search_sale: { en: "Sale", fr: "Vente" },
  search_apartment: { en: "Apartment", fr: "Appartement" },
  search_house: { en: "House", fr: "Maison" },
  search_villa: { en: "Villa", fr: "Villa" },
  search_land: { en: "Land", fr: "Terrain" },
  search_commercial: { en: "Commercial", fr: "Commercial" },
  home_greeting: { en: "Hello 👋", fr: "Bonjour 👋" },
  home_greeting_subtitle: { en: "Find your ideal property", fr: "Trouvez votre bien idéal" },
  home_search_placeholder: { en: "Search by city, district...", fr: "Rechercher par ville, quartier..." },
  home_hero_badge: { en: "Platform #1 in Ivory Coast", fr: "Plateforme N°1 en Côte d' Ivoire" },
  home_hero_title: { en: "Find your ideal property", fr: "Trouvez votre propriété idéale" },
  home_hero_subtitle: { en: "Discover the best real estate offers in Ivory Coast", fr: "Découvrez les meilleures offres immobilières en Côte d' Ivoire" },
  home_property_type: { en: "Property type", fr: "Type de bien" },
  home_price_range: { en: "Price range", fr: "Gamme de prix" },
  home_search_button: { en: "Search", fr: "Rechercher" },
  home_featured_title: { en: "Featured Properties", fr: "Biens en vedette" },
  home_featured_subtitle: { en: "The best properties of the moment", fr: "Les meilleures propriétés du moment" },
  home_see_all: { en: "See all", fr: "Voir tout" },
  home_featured_badge: { en: "FEATURED", fr: "VEDETTE" },
  home_recent_title: { en: "Recently Added", fr: "Récemment ajoutés" },
  home_recent_subtitle: { en: "New properties available", fr: "Nouvelles propriétés disponibles" },
  home_footer_description: { en: "Your trusted real estate platform in Ivory Coast", fr: "Votre plateforme immobilière de confiance en Côte d'Ivoire" },
  home_footer_quick_links: { en: "Quick Links", fr: "Liens rapides" },
  home_footer_support: { en: "Support", fr: "Support" },
  home_footer_contact: { en: "Contact", fr: "Contact" },
  home_footer_help: { en: "Help", fr: "Aide" },
  home_footer_follow: { en: "Follow us", fr: "Suivez-nous" },
  home_footer_copyright: { en: "© 2025 ImmoCI. All rights reserved.", fr: "© 2025 ImmoCI. Tous droits réservés." },
  home_footer_dashboard: { en: "Dashboard", fr: "Dashboard" },
  home_footer_admin: { en: "Admin", fr: "Admin" },
  chat_support_agent: { en: "Support Agent", fr: "Agent de support" },
  chat_automated_assistant: { en: "Automated Assistant", fr: "Assistant Automatisé" },
  chat_reply_in_minutes: { en: "We usually reply in a few minutes", fr: "Nous répondons généralement en quelques minutes" },
  chat_agents_offline: { en: "Agents are currently offline", fr: "Les agents sont actuellement hors ligne" },
  chat_agent_online: { en: "Agent Online", fr: "Agent en ligne" },
  chat_agent_offline_ai: { en: "Agent Offline · AI Active", fr: "Agent hors ligne · IA Active" },
  chat_ai_active: { en: "AI assistant active", fr: "Assistant IA actif" },
  chat_ai_banner_text: { en: "Our support team is currently unavailable. You are now chatting with our AI assistant.", fr: "Notre équipe de support est actuellement indisponible. Vous discutez maintenant avec notre assistant IA." },
  chat_help_title: { en: "How can we help you?", fr: "Comment pouvons-nous vous aider?" },
  chat_fill_details: { en: "Please fill in your details to start a chat.", fr: "Veuillez remplir vos coordonnées pour démarrer une discussion." },
  chat_your_name: { en: "Your Name *", fr: "Votre nom *" },
  chat_phone_optional: { en: "Phone Number (Optional)", fr: "Numéro de téléphone (Optionnel)" },
  chat_your_issue: { en: "What is your issue?", fr: "Quel est votre problème?" },
  chat_start_button: { en: "Start Chat", fr: "Démarrer la discussion" },
  chat_type_message: { en: "Type a message...", fr: "Tapez un message..." },
  chat_backend_unavailable: { en: "Service Unavailable", fr: "Service indisponible" },
  chat_backend_unavailable_message: { en: "The chat service is currently unavailable. Please try again later.", fr: "Le service de discussion est actuellement indisponible. Veuillez réessayer plus tard." },
  property_not_found: { en: "Property not found", fr: "Propriété introuvable" },
  property_per_month: { en: "/month", fr: "/mois" },
  property_for_sale: { en: "For Sale", fr: "À vendre" },
  property_for_rent: { en: "For Rent", fr: "À louer" },
  property_bedrooms_short: { en: "bd", fr: "ch" },
  property_bathrooms_short: { en: "ba", fr: "sdb" },
  property_description: { en: "Description", fr: "Description" },
  property_features: { en: "Features", fr: "Caractéristiques" },
  property_agent: { en: "Agent", fr: "Agent" },
  property_contact_agent: { en: "Contact Agent", fr: "Contacter l'agent" },
  property_card_featured: { en: "FEATURED", fr: "VEDETTE" },
  property_card_sale: { en: "SALE", fr: "VENTE" },
  property_card_rent: { en: "RENT", fr: "LOCATION" },
  search_no_properties: { en: "No properties found", fr: "Aucun bien trouvé" },
  search_filters_title: { en: "Filters", fr: "Filtres" },
  search_filter_property_type: { en: "Property Type", fr: "Type de bien" },
  search_filter_status: { en: "Status", fr: "Statut" },
  search_filter_bedrooms: { en: "Bedrooms", fr: "Chambres" },
  search_filter_bathrooms: { en: "Bathrooms", fr: "Salles de bain" },
  search_filter_all: { en: "All", fr: "Tous" },
  search_filter_all_fem: { en: "All", fr: "Toutes" },
  add_property_title: { en: "List Your Property", fr: "Publier votre bien" },
  add_property_subtitle: { en: "Fill in the details to list your property", fr: "Remplissez les détails pour publier votre bien" },
  add_property_basic_info: { en: "Basic Information", fr: "Informations de base" },
  add_property_title_label: { en: "Property Title", fr: "Titre du bien" },
  add_property_title_placeholder: { en: "e.g., Modern 3BR Apartment in Cocody", fr: "ex: Appartement moderne 3 chambres à Cocody" },
  add_property_description_label: { en: "Description", fr: "Description" },
  add_property_description_placeholder: { en: "Describe your property...", fr: "Décrivez votre bien..." },
  add_property_type_label: { en: "Property Type", fr: "Type de bien" },
  add_property_status_label: { en: "Listing Type", fr: "Type d'annonce" },
  add_property_price_label: { en: "Price (XOF)", fr: "Prix (XOF)" },
  add_property_price_placeholder: { en: "Enter price", fr: "Entrez le prix" },
  add_property_details: { en: "Property Details", fr: "Détails du bien" },
  add_property_bedrooms_label: { en: "Bedrooms", fr: "Chambres" },
  add_property_bathrooms_label: { en: "Bathrooms", fr: "Salles de bain" },
  add_property_area_label: { en: "Area (m²)", fr: "Surface (m²)" },
  add_property_area_placeholder: { en: "Enter area", fr: "Entrez la surface" },
  add_property_location: { en: "Location", fr: "Localisation" },
  add_property_address_label: { en: "Address", fr: "Adresse" },
  add_property_address_placeholder: { en: "Street address", fr: "Adresse de la rue" },
  add_property_city_label: { en: "City", fr: "Ville" },
  add_property_city_placeholder: { en: "e.g., Abidjan", fr: "ex: Abidjan" },
  add_property_district_label: { en: "District", fr: "Quartier" },
  add_property_district_placeholder: { en: "e.g., Cocody", fr: "ex: Cocody" },
  add_property_features_label: { en: "Features", fr: "Caractéristiques" },
  add_property_features_placeholder: { en: "Add a feature (e.g., Swimming Pool)", fr: "Ajouter une caractéristique (ex: Piscine)" },
  add_property_add_feature: { en: "Add Feature", fr: "Ajouter" },
  add_property_contact: { en: "Contact Information", fr: "Informations de contact" },
  add_property_name_label: { en: "Your Name", fr: "Votre nom" },
  add_property_name_placeholder: { en: "Enter your name", fr: "Entrez votre nom" },
  add_property_phone_label: { en: "Phone Number", fr: "Numéro de téléphone" },
  add_property_phone_placeholder: { en: "Enter phone number", fr: "Entrez le numéro de téléphone" },
  add_property_submit: { en: "Submit Property", fr: "Publier le bien" },
  add_property_success: { en: "Property listed successfully!", fr: "Bien publié avec succès!" },
  add_property_error: { en: "Please fill all required fields", fr: "Veuillez remplir tous les champs requis" },
  add_property_cta: { en: "List your property to sell or rent", fr: "Publiez votre bien à vendre ou à louer" },
  add_property_media: { en: "Photos & Media", fr: "Photos & Médias" },
  add_property_photos_label: { en: "Property Photos (3 required)", fr: "Photos du bien (3 requises)" },
  add_property_video_label: { en: "Property Video (optional)", fr: "Vidéo du bien (optionnel)" },
  add_property_document_label: { en: "Property Document (required)", fr: "Document du bien (requis)" },
  add_property_add_photo: { en: "Add Photo", fr: "Ajouter une photo" },
  add_property_add_video: { en: "Add Video", fr: "Ajouter une vidéo" },
  add_property_add_document: { en: "Add Document", fr: "Ajouter un document" },
  add_property_payment: { en: "Payment", fr: "Paiement" },
  add_property_payment_desc: { en: "Pay 10,000 XOF to list your property", fr: "Payez 10 000 XOF pour publier votre bien" },
  add_property_select_payment: { en: "Select Payment Method", fr: "Sélectionner le mode de paiement" },
  add_property_proceed_payment: { en: "Proceed to Payment", fr: "Procéder au paiement" },
  add_property_payment_success: { en: "Payment successful! Your property is now listed.", fr: "Paiement réussi! Votre bien est maintenant publié." },
  add_property_payment_error: { en: "Payment failed. Please try again.", fr: "Échec du paiement. Veuillez réessayer." },
  add_property_media_error: { en: "Please add 3 photos and property document", fr: "Veuillez ajouter 3 photos et le document du bien" },
  add_property_payment_required: { en: "Please select a payment method", fr: "Veuillez sélectionner un mode de paiement" },
  greeting_morning: { en: "Good morning", fr: "Bonjour" },
  greeting_afternoon: { en: "Good afternoon", fr: "Bon après-midi" },
  greeting_evening: { en: "Good evening", fr: "Bonsoir" },
  search_map_view: { en: "Map View", fr: "Vue carte" },
  search_list_view: { en: "List View", fr: "Vue liste" },
  search_close: { en: "Close", fr: "Fermer" },
  use_my_location: { en: "Use My Location", fr: "Utiliser ma position" },
  location_permission_denied: { en: "Permission Denied", fr: "Permission refusée" },
  location_permission_message: { en: "Please enable location services in your device settings to use this feature.", fr: "Veuillez activer les services de localisation dans les paramètres de votre appareil pour utiliser cette fonctionnalité." },
  location_success: { en: "Success", fr: "Succès" },
  location_success_message: { en: "Your location has been detected and filled in.", fr: "Votre position a été détectée et remplie." },
  location_geocode_failed: { en: "Geocoding Failed", fr: "Échec du géocodage" },
  location_geocode_failed_message: { en: "Unable to determine your address. Please enter it manually.", fr: "Impossible de déterminer votre adresse. Veuillez la saisir manuellement." },
  location_error: { en: "Error", fr: "Erreur" },
  location_error_message: { en: "Failed to get your location. Please try again or enter manually.", fr: "Échec de l'obtention de votre position. Veuillez réessayer ou saisir manuellement." },
  dashboard_pending_submissions_title: { en: "Pending Submissions", fr: "Soumissions en attente" },
  dashboard_properties_to_verify: { en: "properties to verify", fr: "propriétés à vérifier" },
  dashboard_no_pending: { en: "No pending submissions", fr: "Aucune soumission en attente" },
  status_pending: { en: "Pending", fr: "En attente" },
  media_photos: { en: "photos", fr: "photos" },
  media_video: { en: "Video", fr: "Vidéo" },
  media_document: { en: "Document", fr: "Document" },
  payment_label: { en: "Payment:", fr: "Paiement:" },
  action_approve: { en: "Approve", fr: "Approuver" },
  action_reject: { en: "Reject", fr: "Rejeter" },
  reject_reason_invalid_doc: { en: "Invalid document", fr: "Document invalide" },
  stat_active_listings: { en: "Active Listings", fr: "Annonces actives" },
  stat_total_views: { en: "Total Views", fr: "Vues totales" },
  stat_favorites: { en: "Favorites", fr: "Favoris" },
  stat_conversion_rate: { en: "Conversion Rate", fr: "Taux de conversion" },
  action_add: { en: "Add", fr: "Ajouter" },
  dashboard_no_active_listings: { en: "No active listings", fr: "Aucune annonce active" },
  dashboard_add_property_button: { en: "Add Property", fr: "Ajouter une propriété" },
  dashboard_saved_properties: { en: "saved properties", fr: "propriétés sauvegardées" },
  action_explore_properties: { en: "Explore Properties", fr: "Explorer les propriétés" },
  dashboard_applications_title: { en: "My Applications", fr: "Mes candidatures" },
  dashboard_applications_subtitle: { en: "Track your rental applications", fr: "Suivi de vos dossiers de location" },
  dashboard_no_applications: { en: "No active applications", fr: "Aucune candidature en cours" },
  dashboard_applications_empty_hint: { en: "Contact a landlord to apply", fr: "Contactez un propriétaire pour déposer un dossier" },
  role_landlord_verified: { en: "Verified Landlord", fr: "Propriétaire Vérifié" },
  role_tenant: { en: "Tenant", fr: "Locataire" },
  profile_stat_listings: { en: "Listings", fr: "Annonces" },
  profile_stat_views: { en: "Views", fr: "Vues" },
  profile_stat_applications: { en: "Applications", fr: "Dossiers" },
  settings_personal_info: { en: "Personal Information", fr: "Informations personnelles" },
  settings_edit_profile_subtitle: { en: "Edit your profile", fr: "Modifier votre profil" },
  settings_preferences: { en: "Preferences", fr: "Préférences" },
  settings_lang_notif: { en: "Language, notifications", fr: "Langue, notifications" },
  settings_logout_subtitle: { en: "Log out of your account", fr: "Se déconnecter du compte" },
  dashboard_title: { en: "ImmoCI Dashboard", fr: "ImmoCI Dashboard" },
  dashboard_admin_panel: { en: "Admin Panel", fr: "Admin Panel" },
  dashboard_back_to_site: { en: "← Back to site", fr: "← Retour au site" },
  dashboard_subtitle_landlord: { en: "Manage your property listings", fr: "Gérez vos annonces immobilières" },
  dashboard_subtitle_tenant: { en: "Find your favorite properties", fr: "Retrouvez vos coups de cœur" },
  role_tenant_space: { en: "Tenant Space", fr: "Espace Locataire" },
  role_landlord_space: { en: "Landlord Space", fr: "Espace Propriétaire" },
  tab_pending: { en: "Pending", fr: "En attente" },
  tab_applications: { en: "Applications", fr: "Candidatures" },
  add_property_transaction_id: { en: "Transaction ID", fr: "ID de transaction" },
  add_property_transaction_id_placeholder: { en: "Enter transaction ID", fr: "Entrez l'ID de transaction" },
  add_property_use_my_location: { en: "Use My Location", fr: "Utiliser ma position" },
  add_property_video_added: { en: "Video added", fr: "Vidéo ajoutée" },
  add_property_document_added: { en: "Document added", fr: "Document ajouté" },
  add_property_skip_dev: { en: "Skip (Dev)", fr: "Passer (Dev)" },
  add_property_select_city: { en: "Select City", fr: "Sélectionner une ville" },
  add_property_select_district: { en: "Select District", fr: "Sélectionner un quartier" },
  add_property_dev_success: { en: "Dev property submitted successfully", fr: "Bien de test publié avec succès" },
  add_property_dev_error: { en: "Failed to submit dev property", fr: "Échec de la publication du bien de test" },
  admin_nav_dashboard: { en: "Dashboard", fr: "Tableau de bord" },
  admin_nav_analytics: { en: "Analytics", fr: "Analytique" },
  admin_nav_properties: { en: "Properties", fr: "Propriétés" },
  admin_nav_documents: { en: "Documents", fr: "Documents" },
  admin_nav_users: { en: "Users", fr: "Utilisateurs" },
  admin_nav_staff: { en: "Staff", fr: "Personnel" },
  admin_nav_support: { en: "Live Chat", fr: "Chat en direct" },
  admin_nav_reports: { en: "Reports", fr: "Rapports" },
  admin_nav_integrations: { en: "Integrations", fr: "Intégrations" },
  admin_nav_settings: { en: "Settings", fr: "Paramètres" },
  admin_main_menu: { en: "MAIN MENU", fr: "MENU PRINCIPAL" },
  admin_management: { en: "MANAGEMENT", fr: "GESTION" },
  admin_other: { en: "OTHER", fr: "AUTRE" },
  admin_back_to_app: { en: "Back to App", fr: "Retour à l'application" },
  admin_search_placeholder: { en: "Search admin...", fr: "Recherche admin..." },
  admin_super_admin: { en: "Super Admin", fr: "Super Administrateur" },
  dash_greeting_morning: { en: "Good morning", fr: "Bonjour" },
  dash_greeting_afternoon: { en: "Good afternoon", fr: "Bon après-midi" },
  dash_greeting_evening: { en: "Good evening", fr: "Bonsoir" },
  dash_subtitle: { en: "Here's what's happening with your properties today.", fr: "Voici ce qui se passe avec vos propriétés aujourd'hui." },
  dash_search_placeholder: { en: "Search anything...", fr: "Rechercher..." },
  dash_nav_overview: { en: "Overview", fr: "Vue d'ensemble" },
  dash_nav_listings: { en: "Listings", fr: "Annonces" },
  dash_nav_analytics: { en: "Analytics", fr: "Analytique" },
  dash_nav_ai_assistant: { en: "AI Assistant", fr: "Assistant IA" },
  dash_nav_pending: { en: "Pending", fr: "En attente" },
  dash_nav_favorites: { en: "Favorites", fr: "Favoris" },
  dash_nav_settings: { en: "Settings", fr: "Paramètres" },
  dash_nav_back_site: { en: "Back to site", fr: "Retour au site" },
  dash_kpi_revenue: { en: "Total Revenue", fr: "Revenu total" },
  dash_kpi_listings: { en: "Active Listings", fr: "Annonces actives" },
  dash_kpi_views: { en: "Total Views", fr: "Vues totales" },
  dash_kpi_conversion: { en: "Conversion Rate", fr: "Taux de conversion" },
  dash_kpi_vs_last: { en: "vs last month", fr: "vs mois dernier" },
  dash_period_today: { en: "Today", fr: "Aujourd'hui" },
  dash_period_7d: { en: "7 Days", fr: "7 Jours" },
  dash_period_30d: { en: "30 Days", fr: "30 Jours" },
  dash_period_90d: { en: "90 Days", fr: "90 Jours" },
  dash_chart_title: { en: "Revenue Overview", fr: "Aperçu des revenus" },
  dash_chart_revenue: { en: "Revenue", fr: "Revenus" },
  dash_chart_views: { en: "Views", fr: "Vues" },
  dash_ai_title: { en: "AI Insights", fr: "Analyses IA" },
  dash_ai_subtitle: { en: "Powered by ImmoCI Intelligence", fr: "Alimenté par l'intelligence ImmoCI" },
  dash_ai_insight_1: { en: "Revenue increased 23.5% compared to last month. Cocody and Plateau districts driving growth.", fr: "Les revenus ont augmenté de 23,5% par rapport au mois dernier. Les quartiers Cocody et Plateau portent la croissance." },
  dash_ai_insight_2: { en: "Cocody district shows highest demand — consider premium pricing for new listings.", fr: "Le quartier de Cocody affiche la plus forte demande — envisagez un prix premium pour les nouvelles annonces." },
  dash_ai_insight_3: { en: "3 listings need photo updates for better conversion rates.", fr: "3 annonces nécessitent une mise à jour des photos pour améliorer les taux de conversion." },
  dash_ai_ask: { en: "Ask AI anything...", fr: "Demandez à l'IA..." },
  dash_top_properties: { en: "Top Performing Properties", fr: "Propriétés les plus performantes" },
  dash_col_property: { en: "Property", fr: "Propriété" },
  dash_col_views: { en: "Views", fr: "Vues" },
  dash_col_favs: { en: "Favorites", fr: "Favoris" },
  dash_col_rate: { en: "Conv. Rate", fr: "Taux Conv." },
  dash_col_status: { en: "Status", fr: "Statut" },
  dash_col_action: { en: "Action", fr: "Action" },
  dash_status_active: { en: "Active", fr: "Actif" },
  dash_status_pending: { en: "Pending", fr: "En attente" },
  dash_status_sold: { en: "Sold", fr: "Vendu" },
  dash_activity_title: { en: "Recent Activity", fr: "Activité récente" },
  dash_activity_new_view: { en: "New view on", fr: "Nouvelle vue sur" },
  dash_activity_new_fav: { en: "Added to favorites:", fr: "Ajouté aux favoris :" },
  dash_activity_price_change: { en: "Price updated for", fr: "Prix mis à jour pour" },
  dash_activity_new_inquiry: { en: "New inquiry for", fr: "Nouvelle demande pour" },
  dash_theme_dark: { en: "Dark", fr: "Sombre" },
  dash_theme_light: { en: "Light", fr: "Clair" },
  dash_lang_en: { en: "EN", fr: "EN" },
  dash_lang_fr: { en: "FR", fr: "FR" },
  dash_view_all: { en: "View All", fr: "Voir tout" },
  dash_this_week: { en: "this week", fr: "cette semaine" },
  auth_gate_badge: { en: "SELLER SPACE", fr: "ESPACE VENDEURS" },
  auth_gate_title: { en: "Sign in to list a property", fr: "Connectez-vous pour publier une annonce" },
  auth_gate_subtitle: { en: "To guarantee the safety and authenticity of listings on ImmoCI, you must sign in or create a verified account before submitting a property.", fr: "Pour garantir la sécurité et l'authenticité des offres sur ImmoCI, vous devez vous connecter ou créer un compte vérifié avant de soumettre un bien." },
  auth_benefit_1_title: { en: "#1 Visibility in Ivory Coast", fr: "Visibilité N°1 en Côte d'Ivoire" },
  auth_benefit_1_desc: { en: "Reach thousands of qualified buyers and tenants across Abidjan and all of Côte d'Ivoire.", fr: "Diffusez vos biens auprès de milliers d'acheteurs et locataires actifs à Abidjan et partout en Côte d'Ivoire." },
  auth_benefit_2_title: { en: "Direct contacts & instant alerts", fr: "Contacts directs & alertes instantanées" },
  auth_benefit_2_desc: { en: "Receive buyer inquiries directly through WhatsApp, Phone, and Email with zero hassle.", fr: "Recevez directement les demandes d'acheteurs par WhatsApp, téléphone et email sans commission abusive." },
  auth_benefit_3_title: { en: "Dashboard & autonomous management", fr: "Tableau de bord & gestion autonome" },
  auth_benefit_3_desc: { en: "Update pricing, manage photo galleries, and track listing view analytics in real-time.", fr: "Modifiez vos prix, photos et suivez les statistiques de vos annonces en temps réel." },
  auth_gate_login_btn: { en: "Sign In / Create Account", fr: "Se connecter / Créer un compte" },
  auth_gate_browse_btn: { en: "Browse Listings", fr: "Explorer les biens" },
  admin_recent_activity: { en: "Recent Activity", fr: "Activité récente" },
  admin_recent_activity_subtitle: { en: "Latest platform activities", fr: "Dernières activités de la plateforme" },
  admin_load_more: { en: "Load more", fr: "Charger plus" },
  admin_just_now: { en: "Just now", fr: "À l'instant" },
  admin_min_ago: { en: "min ago", fr: "min" },
  admin_hours_ago: { en: "hours ago", fr: "heures" },
  admin_days_ago: { en: "days ago", fr: "jours" },
  admin_quick_actions: { en: "Quick Actions", fr: "Actions rapides" },
  admin_quick_actions_subtitle: { en: "Manage your platform", fr: "Gérez votre plateforme" },
  admin_manage_properties: { en: "Manage Properties", fr: "Gérer les propriétés" },
  admin_manage_users: { en: "Manage Users", fr: "Gérer les utilisateurs" },
  admin_view_reports: { en: "View Reports", fr: "Voir les rapports" },
  admin_ai_assistant: { en: "AI Insight Assistant", fr: "Assistant d'analyse IA" },
  admin_ai_assistant_desc: { en: "Ask questions about your dashboard data, e.g., \"Which month had the best growth?\" or \"Summarize my revenue trends.\"", fr: "Posez des questions sur vos données, ex: \"Quel mois a eu la meilleure croissance ?\" ou \"Résume les tendances de revenus.\"" },
  admin_ai_placeholder: { en: "Ask about your data...", fr: "Posez une question sur vos données..." },
  admin_ai_chip_kpis: { en: "Summarize KPIs", fr: "Résumer les KPIs" },
  admin_ai_chip_growth: { en: "User Growth Trend", fr: "Tendance de croissance" },
  admin_ai_chip_type: { en: "Popular Property Type", fr: "Type de bien populaire" },
  admin_ai_ask_another: { en: "Ask another question", fr: "Poser une autre question" },
  admin_ai_analysis_title: { en: "AI Analysis", fr: "Analyse IA" },
  admin_ai_insights: { en: "AI Insights", fr: "Analyses IA" },
  admin_ai_insights_sub: { en: "AI-generated platform report", fr: "Rapport généré par l'IA" },
  admin_ai_generate: { en: "Generate", fr: "Générer" },
  admin_ai_no_report: { en: "No report generated", fr: "Aucun rapport généré" },
  admin_ai_no_report_sub: { en: "Press \"Generate\" to get an AI analysis of the platform.", fr: "Appuyez sur \"Générer\" pour obtenir une analyse IA de la plateforme." },
  admin_ai_analyzing: { en: "Analyzing platform data...", fr: "Analyse des données en cours..." },
  admin_revenue_analytics: { en: "Revenue Analytics", fr: "Analytique des Revenus" },
  admin_revenue_trend: { en: "Monthly revenue trend", fr: "Tendance mensuelle des revenus" },
  admin_average: { en: "Average", fr: "Moyenne" },
  admin_total: { en: "Total", fr: "Total" },
  admin_peak: { en: "Peak", fr: "Pic" },
  admin_monthly_growth: { en: "Monthly Growth", fr: "Croissance Mensuelle" },
  admin_monthly_growth_sub: { en: "Properties and users over time", fr: "Évolution des biens et utilisateurs" },
  admin_properties_label: { en: "Properties", fr: "Propriétés" },
  admin_users_label: { en: "Users", fr: "Utilisateurs" },
  admin_performance_distribution: { en: "Performance Distribution", fr: "Distribution de Performance" },
  admin_property_distribution: { en: "Property Distribution", fr: "Distribution des Propriétés" },
  admin_by_property_type: { en: "By property type · Q2 2026", fr: "Par type de bien · T2 2026" },
  admin_exceptional: { en: "Exceptional", fr: "Exceptionnel" },
  admin_needs_focus: { en: "Needs Focus", fr: "À optimiser" },
  admin_underperforming: { en: "Underperforming", fr: "Sous-performance" },
  admin_satisfactory: { en: "Satisfactory", fr: "Satisfaisant" },
  admin_outstanding: { en: "Outstanding", fr: "Remarquable" },
  admin_villas: { en: "Villas", fr: "Villas" },
  admin_land: { en: "Land", fr: "Terrains" },
  admin_commercial: { en: "Commercial", fr: "Commercial" },
  admin_apartments: { en: "Apartments", fr: "Appartements" },
  admin_stat_total_properties: { en: "Total Properties", fr: "Total Propriétés" },
  admin_stat_active_listings: { en: "Active listings", fr: "Annonces actives" },
  admin_stat_total_users: { en: "Total Users", fr: "Total Utilisateurs" },
  admin_stat_active_accounts: { en: "Active accounts", fr: "Comptes actifs" },
  admin_stat_pending_docs: { en: "Pending Docs", fr: "Docs en attente" },
  admin_stat_verification_req: { en: "Verification required", fr: "Vérification requise" },
  admin_stat_revenue: { en: "Total Revenue", fr: "Revenus Totaux" },
  admin_stat_revenue_sub: { en: "Platform Volume (FCFA)", fr: "Volume Plateforme (FCFA)" },
  admin_search_properties: { en: "Search properties...", fr: "Rechercher des biens..." },
  admin_filters: { en: "Filters", fr: "Filtres" },
  admin_add_property: { en: "Add Property", fr: "Ajouter un bien" },
  admin_th_property: { en: "Property", fr: "Propriété" },
  admin_th_location: { en: "Location", fr: "Emplacement" },
  admin_th_price: { en: "Price", fr: "Prix" },
  admin_th_type: { en: "Type", fr: "Type" },
  admin_th_status: { en: "Status", fr: "Statut" },
  admin_th_action: { en: "Action", fr: "Action" },
  admin_no_properties: { en: "No properties listed yet", fr: "Aucune propriété répertoriée" },
  admin_no_properties_sub: { en: "Properties submitted by users or agents will appear here.", fr: "Les propriétés soumises par les utilisateurs ou agents apparaîtront ici." },
  admin_all_docs_verified: { en: "All documents verified", fr: "Tous les documents sont vérifiés" },
  admin_all_docs_verified_sub: { en: "Great job! There are currently no pending documents to review.", fr: "Bravo ! Aucun document en attente de vérification pour le moment." },
  admin_available_reports: { en: "Available Reports", fr: "Rapports Disponibles" },
  admin_staff_management: { en: "Staff Management", fr: "Gestion du Personnel" },
  admin_staff_management_sub: { en: "Manage team members and authorization roles", fr: "Gérez les membres de l'équipe et leurs autorisations" },
  admin_add_staff_member: { en: "Add Staff Member", fr: "Ajouter un membre" },
  admin_search_staff: { en: "Search staff members...", fr: "Rechercher du personnel..." },
  admin_total_staff: { en: "Total Staff", fr: "Total Personnel" },
  admin_active: { en: "Active", fr: "Actif" },
  admin_managers: { en: "Managers", fr: "Managers" },
  admin_agents: { en: "Agents", fr: "Agents" },
  admin_th_staff_member: { en: "Staff Member", fr: "Membre" },
  admin_th_email: { en: "Email", fr: "Email" },
  admin_th_role: { en: "Role", fr: "Rôle" },
  admin_th_department: { en: "Department", fr: "Département" },
  admin_th_hire_date: { en: "Hire Date", fr: "Date d'embauche" },
  admin_th_last_active: { en: "Last Active", fr: "Dernière activité" },
  admin_th_actions: { en: "Actions", fr: "Actions" },
  admin_analytics_overview: { en: "Analytics & Insights Overview", fr: "Aperçu Analytique & Performances" },
  admin_analytics_overview_sub: { en: "Deep metrics on revenue, platform engagement, and conversion rates", fr: "Métriques détaillées sur les revenus, l'engagement et la conversion" },
  admin_support_desk: { en: "Support & Tickets Desk", fr: "Support & Centre de Tickets" },
  admin_support_desk_sub: { en: "Triage live customer questions, dispute escalations, and inquiries", fr: "Gestion des demandes clients, signalements et litiges" },
  admin_verified: { en: "Verified", fr: "Vérifié" },
  dept_all: { en: "All Departments", fr: "Tous les départements" },
  dept_operations: { en: "Operations & Logistics", fr: "Opérations & Logistique" },
  dept_legal: { en: "Legal & Compliance", fr: "Juridique & Conformité" },
  dept_sales: { en: "Sales & Commercial", fr: "Commercial & Ventes" },
  dept_support: { en: "Customer Support", fr: "Support Client" },
  dept_finance: { en: "Finance & Billing", fr: "Finance & Facturation" },
  dept_platform_admin: { en: "Platform Administration", fr: "Administration Plateforme" },
  dept_marketing: { en: "Marketing & Growth", fr: "Marketing & Croissance" },
  role_super_admin: { en: "Super Admin", fr: "Super Administrateur" },
  role_operations_mgr: { en: "Operations Manager", fr: "Responsable Opérations" },
  role_legal_officer: { en: "Legal Officer", fr: "Chargé Juridique" },
  role_sales_agent: { en: "Sales Agent", fr: "Agent Commercial" },
  role_support_specialist: { en: "Support Specialist", fr: "Spécialiste Support" },
  role_finance_officer: { en: "Finance Officer", fr: "Responsable Finance" },
  admin_switch_role_title: { en: "Switch Department & Access Level", fr: "Changer de Département & Rôle" },
  admin_switch_role_sub: { en: "Select an access role to test permissions and workflows across the platform.", fr: "Sélectionnez un rôle pour tester les autorisations et flux de travail." },
  admin_current_access: { en: "Active Access Mode", fr: "Mode d'accès actif" },
  admin_permissions_label: { en: "Permissions & Scope", fr: "Autorisations & Portée" },
  admin_unrestricted_access: { en: "Full Platform Access (All Sections)", fr: "Accès complet plateforme (Toutes sections)" },
  admin_tickets_title: { en: "Live Helpdesk & User Inquiries", fr: "Assistance & Demandes Utilisateurs" },
  admin_reply_placeholder: { en: "Type your official response to customer...", fr: "Tapez votre réponse officielle au client..." },
  admin_send_reply: { en: "Send Reply", fr: "Envoyer la réponse" },
  admin_ai_suggest_reply: { en: "AI Draft Reply", fr: "Rédiger avec l'IA" },
  admin_ticket_status_open: { en: "Open", fr: "Ouvert" },
  admin_ticket_status_in_progress: { en: "In Progress", fr: "En cours" },
  admin_ticket_status_resolved: { en: "Resolved", fr: "Résolu" },
  admin_report_downloaded: { en: "Report downloaded successfully", fr: "Rapport téléchargé avec succès" },
  admin_download: { en: "Download", fr: "Télécharger" },
  common_save: { en: "Save", fr: "Enregistrer" },
  common_cancel: { en: "Cancel", fr: "Annuler" },
  common_delete: { en: "Delete", fr: "Supprimer" },
  common_edit: { en: "Edit", fr: "Modifier" },
  common_create: { en: "Create", fr: "Créer" },
  common_confirm: { en: "Confirm", fr: "Confirmer" },
  common_back: { en: "Back", fr: "Retour" },
  common_next: { en: "Next", fr: "Suivant" },
  common_close: { en: "Close", fr: "Fermer" },
  common_search: { en: "Search", fr: "Rechercher" },
  common_filter: { en: "Filter", fr: "Filtrer" },
  common_reset: { en: "Reset", fr: "Réinitialiser" },
  common_loading: { en: "Loading...", fr: "Chargement en cours..." },
  common_no_results: { en: "No results found", fr: "Aucun résultat trouvé" },
  common_error: { en: "An error occurred", fr: "Une erreur est survenue" },
  common_success: { en: "Operation successful", fr: "Opération réussie" },
  common_unauthorized: { en: "Access Denied", fr: "Accès Non Autorisé" },
  common_unauthorized_desc: { en: "Your role or current permissions do not allow you to access this section.", fr: "Votre rôle ou vos permissions actuelles ne vous autorisent pas à accéder à cette section." },
  common_return_dashboard: { en: "Back to Dashboard", fr: "Retour au Tableau de Bord" },
  common_export_excel: { en: "Export to Excel (.xlsx)", fr: "Exporter en Excel (.xlsx)" },
  common_yes: { en: "Yes", fr: "Oui" },
  common_no: { en: "No", fr: "Non" },
  audit_page_title: { en: "Audit & Security Trail", fr: "Journal d'Audit & Sécurité" },
  audit_page_sub: { en: "Forensic event logging, role changes, and compliance tracking", fr: "Traçabilité légale, modifications de rôles et détection des intrusions" },
  audit_kpi_total: { en: "Recorded Events", fr: "Événements Enregistrés" },
  audit_kpi_staff: { en: "Staff & Role Changes", fr: "Modifications Staff/Rôles" },
  audit_kpi_properties: { en: "Property Validations", fr: "Vérifications Biens" },
  audit_kpi_alerts: { en: "Security Violations", fr: "Alertes de Sécurité" },
  audit_search_placeholder: { en: "Search audit events by keyword, actor, target...", fr: "Rechercher par mot-clé, auteur, ressource..." },
  audit_filter_all_actions: { en: "All Actions", fr: "Toutes les actions" },
  audit_filter_all_severities: { en: "All Severities", fr: "Toutes les sévérités" },
  audit_filter_24h: { en: "Last 24 Hours", fr: "Dernières 24h" },
  audit_filter_7d: { en: "Last 7 Days", fr: "7 derniers jours" },
  audit_filter_30d: { en: "Last 30 Days", fr: "30 derniers jours" },
  audit_filter_all_time: { en: "All Time", fr: "Tout l'historique" },
  audit_col_id: { en: "Event ID", fr: "ID Audit" },
  audit_col_time: { en: "Timestamp", fr: "Date & Heure" },
  audit_col_action: { en: "Action", fr: "Action" },
  audit_col_severity: { en: "Severity", fr: "Sévérité" },
  audit_col_actor: { en: "Actor", fr: "Auteur" },
  audit_col_target: { en: "Target Resource", fr: "Cible / Ressource" },
  audit_col_details: { en: "Metadata Details", fr: "Métadonnées" },
  audit_inspect_title: { en: "Audit Event Inspection", fr: "Inspection Détaillée de l'Événement" },
  audit_inspect_sub: { en: "Immutable forensic signature & metadata payload", fr: "Signature forensique & métadonnées immuables" },
  audit_toast_exported: { en: "Audit log successfully exported to Excel (.xlsx)", fr: "Journal d'audit exporté avec succès en Excel (.xlsx)" },
  reports_page_title: { en: "Reporting & Operational Audit Center", fr: "Centre de Rapports & Audit d'Activité" },
  reports_page_sub: { en: "Live business analytics and certified Excel workbooks based on real database records", fr: "Analyses réelles du portefeuille et exports de données certifiés OpenXML" },
  reports_tab_revenue: { en: "Revenue & Volume", fr: "Revenus & Volume" },
  reports_tab_inventory: { en: "Property Inventory", fr: "Parc Immobilier" },
  reports_tab_inquiries: { en: "Inquiries & Leads", fr: "Demandes & Visites" },
  reports_tab_customers: { en: "Customers Directory", fr: "Répertoire Clients" },
  reports_tab_staff: { en: "Staff Activity", fr: "Activité Équipe" },
  reports_filter_period: { en: "Period:", fr: "Période :" },
  reports_filter_commune: { en: "District:", fr: "Commune :" },
  reports_filter_type: { en: "Property Type:", fr: "Type de bien :" },
  reports_filter_status: { en: "Status:", fr: "Statut :" },
  reports_export_btn: { en: "Export Report (.xlsx)", fr: "Télécharger Rapport (.xlsx)" },
  reports_export_locked: { en: "Export Locked (Permission reports.export required)", fr: "Export Verrouillé (Permission requise)" },
  staff_page_title: { en: "Staff & Access Management", fr: "Gestion des Collaborateurs & Habilitations" },
  staff_page_sub: { en: "Manage team directory, roles, and granular security permissions", fr: "Répertoire des collaborateurs, attribution des rôles et contrôle d'accès granulaire" },
  staff_add_member: { en: "New Staff Member", fr: "Nouveau Collaborateur" },
  staff_col_name: { en: "Collaborator", fr: "Collaborateur" },
  staff_col_role: { en: "Role", fr: "Rôle" },
  staff_col_department: { en: "Department", fr: "Département" },
  staff_col_permissions: { en: "Permissions", fr: "Permissions" },
  staff_col_status: { en: "Status", fr: "Statut" },
  staff_col_last_active: { en: "Last Active", fr: "Dernière Activité" },
  staff_edit_permissions: { en: "Edit Access & Permissions", fr: "Gérer les Droits d'Accès" },
  staff_toast_saved: { en: "Staff permissions updated successfully", fr: "Permissions mises à jour avec succès" },
  staff_toast_created: { en: "Staff member added successfully", fr: "Collaborateur ajouté avec succès" },
  amenity_swimming_pool: { en: "Swimming Pool", fr: "Piscine" },
  amenity_garden: { en: "Garden", fr: "Jardin" },
  amenity_parking: { en: "Parking", fr: "Parking / Garage" },
  amenity_security: { en: "24/7 Security", fr: "Sécurité 24/7" },
  amenity_air_conditioning: { en: "Air Conditioning", fr: "Climatisation" },
  amenity_furnished: { en: "Furnished", fr: "Meublé" },
  amenity_elevator: { en: "Elevator", fr: "Ascenseur" },
  amenity_balcony: { en: "Balcony / Terrace", fr: "Balcon / Terrasse" },
  amenity_generator: { en: "Backup Generator", fr: "Groupe électrogène" },
  amenity_borehole: { en: "Water Tank / Borehole", fr: "Cuve d'eau / Forage" },
  customer_care_title: { en: "Customer Care", fr: "Service Client" },
  customer_care_tagline: { en: "Here to help you 7 days a week", fr: "À votre service 7j/7" },
  customer_care_disclaimer: { en: "You are connected with ImmoCI Customer Care", fr: "Vous échangez avec le Service Client ImmoCI" },
};

export type TranslationKey = keyof typeof dictionary;

export interface LanguageContextValue {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey | string, fallback?: string) => string;
  isLoaded: boolean;
  isRTL: boolean;
  dir: 'ltr';
}

export const [LanguageProvider, useLanguage] = createContextHook<LanguageContextValue>(() => {
  const [language, setLanguageState] = useState<LanguageCode>('fr');
  const [isLoaded, setIsLoaded] = useState(false);

  // Synchronize HTML document dir and lang on Web
  useEffect(() => {
    if (Platform.OS === 'web' && typeof document !== 'undefined') {
      document.documentElement.lang = language;
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  useEffect(() => {
    let mounted = true;
    const loadLanguage = async () => {
      try {
        const stored = await AsyncStorage.getItem('app_language');
        if (mounted && (stored === 'en' || stored === 'fr')) {
          setLanguageState(stored as LanguageCode);
        } else if (mounted && stored) {
          setLanguageState('fr');
          AsyncStorage.setItem('app_language', 'fr').catch(() => {});
        }
      } catch (error) {
        console.error('Error loading language:', error);
      } finally {
        if (mounted) {
          setIsLoaded(true);
        }
      }
    };
    loadLanguage();
    return () => {
      mounted = false;
    };
  }, []);

  const setLanguage = useCallback(async (lang: LanguageCode) => {
    setLanguageState(lang); // Optimistic update
    try {
      await AsyncStorage.setItem('app_language', lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguage(language === 'fr' ? 'en' : 'fr');
  }, [language, setLanguage]);

  const t = useCallback(
    (key: TranslationKey | string, fallback?: string) => {
      const entry = dictionary[key];
      if (entry) {
        if (entry[language]) return entry[language];
        if (entry.fr) return entry.fr;
        if (entry.en) return entry.en;
      }
      if (fallback !== undefined) {
        return fallback;
      }
      return String(key);
    },
    [language]
  );

  const isRTL = false;
  const dir = 'ltr' as const;

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage,
      t,
      isLoaded,
      isRTL,
      dir,
    }),
    [language, setLanguage, toggleLanguage, t, isLoaded, isRTL, dir]
  );

  return value;
});
