import { useCallback, useState, useEffect, useMemo } from 'react';
import createContextHook from '@nkzw/create-context-hook';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';

export type LanguageCode = 'en' | 'fr' | 'ar';

export interface TranslationEntry {
  en: string;
  fr: string;
  ar: string;
}

export type Dictionary = Record<string, TranslationEntry>;

export const dictionary: Dictionary = {
  nav_home: { en: "Home", fr: "Accueil", ar: "الرئيسية" },
  nav_search: { en: "Search", fr: "Recherche", ar: "بحث" },
  nav_favorites: { en: "Favorites", fr: "Favoris", ar: "المفضلة" },
  nav_profile: { en: "Profile", fr: "Profil", ar: "الملف الشخصي" },
  nav_buy: { en: "Buy", fr: "Acheter", ar: "شراء" },
  nav_rent: { en: "Rent", fr: "Louer", ar: "إيجار" },
  nav_add_property: { en: "Add Property", fr: "Ajouter un bien", ar: "إضافة عقار" },
  nav_login: { en: "Login", fr: "Connexion", ar: "تسجيل الدخول" },
  nav_signup: { en: "Sign Up", fr: "Inscription", ar: "إنشاء حساب" },
  language_english: { en: "English", fr: "Anglais", ar: "English" },
  language_french: { en: "French", fr: "Français", ar: "Français" },
  features_search_title: { en: "Search Properties", fr: "Rechercher des propriétés", ar: "البحث عن عقارات" },
  features_search_desc: { en: "Find your ideal property easily", fr: "Trouvez votre bien idéal facilement", ar: "اعثر على عقارك المثالي بكل سهولة" },
  features_buy_title: { en: "Buy & Rent", fr: "Acheter & Louer", ar: "شراء وإيجار" },
  features_buy_desc: { en: "Buy or rent with confidence", fr: "Achetez ou louez en toute confiance", ar: "اشترِ أو استأجر بكل ثقة وأمان" },
  features_location_title: { en: "Location", fr: "Localisation", ar: "الموقع الجغرافي" },
  features_location_desc: { en: "Explore by neighborhood", fr: "Explorez par quartier", ar: "استكشف العقارات حسب الأحياء والمدن" },
  features_community_title: { en: "Community", fr: "Communauté", ar: "مجتمع موثوق" },
  features_community_desc: { en: "Trusted property owners", fr: "Propriétaires de confiance", ar: "ملاك ووكلاء عقاريون معتمدون" },
  features_security_title: { en: "Guaranteed Security", fr: "Sécurité garantie", ar: "أمان مضمون" },
  features_security_desc: { en: "Secure and verified transactions", fr: "Transactions sécurisées et vérifiées", ar: "معاملات آمنة ومستندات موثقة" },
  features_quick_title: { en: "Quick Service", fr: "Service rapide", ar: "خدمة سريعة" },
  features_quick_desc: { en: "Response within 24 hours", fr: "Réponse sous 24 heures", ar: "استجابة سريعة خلال 24 ساعة" },
  settings_title: { en: "Settings", fr: "Paramètres", ar: "الإعدادات" },
  settings_general: { en: "General", fr: "Général", ar: "عام" },
  settings_language: { en: "Language", fr: "Langue", ar: "اللغة" },
  settings_notifications: { en: "Notifications", fr: "Notifications", ar: "الإشعارات" },
  settings_dark_mode: { en: "Dark Mode", fr: "Mode sombre", ar: "الوضع الليلي" },
  settings_enabled: { en: "Enabled", fr: "Activé", ar: "مفعل" },
  settings_disabled: { en: "Disabled", fr: "Désactivé", ar: "معطل" },
  favorites_title: { en: "My Favorites", fr: "Mes Favoris", ar: "عقاراتي المفضلة" },
  favorites_properties: { en: "properties", fr: "biens", ar: "عقارات" },
  favorites_empty_title: { en: "No favorites", fr: "Aucun favori", ar: "لا توجد مفضلات" },
  favorites_empty_text: { en: "Properties you like will appear here", fr: "Les biens que vous aimez apparaîtront ici", ar: "العقارات التي تعجبك ستظهر هنا" },
  profile_edit: { en: "Edit Profile", fr: "Modifier le profil", ar: "تعديل الملف الشخصي" },
  profile_my_account: { en: "My Account", fr: "Mon Compte", ar: "حسابي" },
  profile_my_favorites: { en: "My Favorites", fr: "Mes Favoris", ar: "مفضلاتي" },
  profile_my_listings: { en: "My Listings", fr: "Mes Annonces", ar: "عقاراتي المعروضة" },
  profile_settings: { en: "Settings", fr: "Paramètres", ar: "الإعدادات" },
  profile_help: { en: "Help & Support", fr: "Aide & Support", ar: "المساعدة والدعم" },
  profile_logout: { en: "Logout", fr: "Déconnexion", ar: "تسجيل الخروج" },
  search_buy: { en: "Buy", fr: "Acheter", ar: "شراء" },
  search_rent: { en: "Rent", fr: "Louer", ar: "إيجار" },
  search_location: { en: "Location", fr: "Localisation", ar: "الموقع" },
  search_any: { en: "Any", fr: "Tous", ar: "الكل" },
  search_properties: { en: "Search Properties", fr: "Rechercher des biens", ar: "البحث في العقارات" },
  search_no_results: { en: "No properties found", fr: "Aucun bien trouvé", ar: "لم يتم العثور على عقارات" },
  search_filters: { en: "Filters", fr: "Filtres", ar: "عوامل التصفية" },
  search_property_type: { en: "Property Type", fr: "Type de bien", ar: "نوع العقار" },
  search_status: { en: "Status", fr: "Statut", ar: "الحالة" },
  search_bedrooms: { en: "Bedrooms", fr: "Chambres", ar: "غرف النوم" },
  search_bathrooms: { en: "Bathrooms", fr: "Salles de bain", ar: "دورات المياه" },
  search_reset: { en: "Reset", fr: "Réinitialiser", ar: "إعادة ضبط" },
  search_apply: { en: "Apply", fr: "Appliquer", ar: "تطبيق" },
  search_all: { en: "All", fr: "Tous", ar: "الكل" },
  search_sale: { en: "Sale", fr: "Vente", ar: "بيع" },
  search_apartment: { en: "Apartment", fr: "Appartement", ar: "شقة" },
  search_house: { en: "House", fr: "Maison", ar: "منزل" },
  search_villa: { en: "Villa", fr: "Villa", ar: "فيلا" },
  search_land: { en: "Land", fr: "Terrain", ar: "أرض" },
  search_commercial: { en: "Commercial", fr: "Commercial", ar: "تجاري" },
  home_greeting: { en: "Hello 👋", fr: "Bonjour 👋", ar: "مرحباً بك 👋" },
  home_greeting_subtitle: { en: "Find your ideal property", fr: "Trouvez votre bien idéal", ar: "اعثر على عقارك المثالي" },
  home_search_placeholder: { en: "Search by city, district...", fr: "Rechercher par ville, quartier...", ar: "ابحث حسب المدينة أو الحي..." },
  home_hero_badge: { en: "Platform #1 in Ivory Coast", fr: "Plateforme N°1 en Côte d' Ivoire", ar: "المنصة العقارية رقم 1 في ساحل العاج" },
  home_hero_title: { en: "Find your ideal property", fr: "Trouvez votre propriété idéale", ar: "اعثر على عقارك المثالي" },
  home_hero_subtitle: { en: "Discover the best real estate offers in Ivory Coast", fr: "Découvrez les meilleures offres immobilières en Côte d' Ivoire", ar: "اكتشف أفضل العروض العقارية الموثوقة في ساحل العاج" },
  home_property_type: { en: "Property type", fr: "Type de bien", ar: "نوع العقار" },
  home_price_range: { en: "Price range", fr: "Gamme de prix", ar: "نطاق السعر" },
  home_search_button: { en: "Search", fr: "Rechercher", ar: "بحث" },
  home_featured_title: { en: "Featured Properties", fr: "Biens en vedette", ar: "عقارات مميزة" },
  home_featured_subtitle: { en: "The best properties of the moment", fr: "Les meilleures propriétés du moment", ar: "أفضل الفرص العقارية المختارة حالياً" },
  home_see_all: { en: "See all", fr: "Voir tout", ar: "عرض الكل" },
  home_featured_badge: { en: "FEATURED", fr: "VEDETTE", ar: "مميز" },
  home_recent_title: { en: "Recently Added", fr: "Récemment ajoutés", ar: "أضيف حديثاً" },
  home_recent_subtitle: { en: "New properties available", fr: "Nouvelles propriétés disponibles", ar: "أحدث العقارات المتاحة في السوق" },
  home_footer_description: { en: "Your trusted real estate platform in Ivory Coast", fr: "Votre plateforme immobilière de confiance en Côte d'Ivoire", ar: "منصتك العقارية الموثوقة في ساحل العاج" },
  home_footer_quick_links: { en: "Quick Links", fr: "Liens rapides", ar: "روابط سريعة" },
  home_footer_support: { en: "Support", fr: "Support", ar: "الدعم والمساعدة" },
  home_footer_contact: { en: "Contact", fr: "Contact", ar: "اتصل بنا" },
  home_footer_help: { en: "Help", fr: "Aide", ar: "مركز المساعدة" },
  home_footer_follow: { en: "Follow us", fr: "Suivez-nous", ar: "تابعنا على" },
  home_footer_copyright: { en: "© 2025 ImmoCI. All rights reserved.", fr: "© 2025 ImmoCI. Tous droits réservés.", ar: "© 2026 ImmoCI. جميع الحقوق محفوظة." },
  home_footer_dashboard: { en: "Dashboard", fr: "Dashboard", ar: "لوحة التحكم" },
  home_footer_admin: { en: "Admin", fr: "Admin", ar: "الإدارة" },
  chat_support_agent: { en: "Support Agent", fr: "Agent de support", ar: "ممثل خدمة العملاء" },
  chat_automated_assistant: { en: "Automated Assistant", fr: "Assistant Automatisé", ar: "المساعد الآلي الذكي" },
  chat_reply_in_minutes: { en: "We usually reply in a few minutes", fr: "Nous répondons généralement en quelques minutes", ar: "نرد عادةً خلال دقائق معدودة" },
  chat_agents_offline: { en: "Agents are currently offline", fr: "Les agents sont actuellement hors ligne", ar: "فريق العمل غير متصل حالياً" },
  chat_agent_online: { en: "Agent Online", fr: "Agent en ligne", ar: "الوكيل متصل الآن" },
  chat_agent_offline_ai: { en: "Agent Offline · AI Active", fr: "Agent hors ligne · IA Active", ar: "الوكيل غير متصل · المساعد الذكي نشط" },
  chat_ai_active: { en: "AI assistant active", fr: "Assistant IA actif", ar: "المساعد الذكي جاهز لمساعدتك" },
  chat_ai_banner_text: { en: "Our support team is currently unavailable. You are now chatting with our AI assistant.", fr: "Notre équipe de support est actuellement indisponible. Vous discutez maintenant avec notre assistant IA.", ar: "فريق الدعم غير متاح حالياً. أنت الآن تتحدث مع المساعد الذكي." },
  chat_help_title: { en: "How can we help you?", fr: "Comment pouvons-nous vous aider?", ar: "كيف يمكننا مساعدتك اليوم؟" },
  chat_fill_details: { en: "Please fill in your details to start a chat.", fr: "Veuillez remplir vos coordonnées pour démarrer une discussion.", ar: "يرجى إدخال بياناتك لبدء المحادثة المباشرة." },
  chat_your_name: { en: "Your Name *", fr: "Votre nom *", ar: "الاسم الكامل *" },
  chat_phone_optional: { en: "Phone Number (Optional)", fr: "Numéro de téléphone (Optionnel)", ar: "رقم الهاتف (اختياري)" },
  chat_your_issue: { en: "What is your issue?", fr: "Quel est votre problème?", ar: "ما هو استفسارك أو طلبك؟" },
  chat_start_button: { en: "Start Chat", fr: "Démarrer la discussion", ar: "بدء المحادثة" },
  chat_type_message: { en: "Type a message...", fr: "Tapez un message...", ar: "اكتب رسالتك هنا..." },
  chat_backend_unavailable: { en: "Service Unavailable", fr: "Service indisponible", ar: "الخدمة غير متوفرة حالياً" },
  chat_backend_unavailable_message: { en: "The chat service is currently unavailable. Please try again later.", fr: "Le service de discussion est actuellement indisponible. Veuillez réessayer plus tard.", ar: "خدمة المحادثة غير متاحة مؤقتاً. يرجى المحاولة لاحقاً." },
  property_not_found: { en: "Property not found", fr: "Propriété introuvable", ar: "العقار غير موجود" },
  property_per_month: { en: "/month", fr: "/mois", ar: "/شهرياً" },
  property_for_sale: { en: "For Sale", fr: "À vendre", ar: "للبيع" },
  property_for_rent: { en: "For Rent", fr: "À louer", ar: "للإيجار" },
  property_bedrooms_short: { en: "bd", fr: "ch", ar: "غرفة" },
  property_bathrooms_short: { en: "ba", fr: "sdb", ar: "حمام" },
  property_description: { en: "Description", fr: "Description", ar: "وصف العقار" },
  property_features: { en: "Features", fr: "Caractéristiques", ar: "المميزات والمرافق" },
  property_agent: { en: "Agent", fr: "Agent", ar: "الوكيل العقاري" },
  property_contact_agent: { en: "Contact Agent", fr: "Contacter l'agent", ar: "تواصل مع الوكيل" },
  property_card_featured: { en: "FEATURED", fr: "VEDETTE", ar: "مميز" },
  property_card_sale: { en: "SALE", fr: "VENTE", ar: "بيع" },
  property_card_rent: { en: "RENT", fr: "LOCATION", ar: "إيجار" },
  search_no_properties: { en: "No properties found", fr: "Aucun bien trouvé", ar: "لم يتم العثور على أي عقار" },
  search_filters_title: { en: "Filters", fr: "Filtres", ar: "عوامل التصفية" },
  search_filter_property_type: { en: "Property Type", fr: "Type de bien", ar: "نوع العقار" },
  search_filter_status: { en: "Status", fr: "Statut", ar: "الحالة" },
  search_filter_bedrooms: { en: "Bedrooms", fr: "Chambres", ar: "غرف النوم" },
  search_filter_bathrooms: { en: "Bathrooms", fr: "Salles de bain", ar: "دورات المياه" },
  search_filter_all: { en: "All", fr: "Tous", ar: "الكل" },
  search_filter_all_fem: { en: "All", fr: "Toutes", ar: "الكل" },
  add_property_title: { en: "List Your Property", fr: "Publier votre bien", ar: "نشر عقار جديد" },
  add_property_subtitle: { en: "Fill in the details to list your property", fr: "Remplissez les détails pour publier votre bien", ar: "املأ تفاصيل العقار لعرضه للبيع أو الإيجار" },
  add_property_basic_info: { en: "Basic Information", fr: "Informations de base", ar: "المعلومات الأساسية" },
  add_property_title_label: { en: "Property Title", fr: "Titre du bien", ar: "عنوان الإعلان" },
  add_property_title_placeholder: { en: "e.g., Modern 3BR Apartment in Cocody", fr: "ex: Appartement moderne 3 chambres à Cocody", ar: "مثال: شقة حديثة 3 غرف في كوكودي" },
  add_property_description_label: { en: "Description", fr: "Description", ar: "وصف العقار" },
  add_property_description_placeholder: { en: "Describe your property...", fr: "Décrivez votre bien...", ar: "صف مميزات ومواصفات عقارك..." },
  add_property_type_label: { en: "Property Type", fr: "Type de bien", ar: "نوع العقار" },
  add_property_status_label: { en: "Listing Type", fr: "Type d'annonce", ar: "نوع المعاملة" },
  add_property_price_label: { en: "Price (XOF)", fr: "Prix (XOF)", ar: "السعر (فرنك سيفا XOF)" },
  add_property_price_placeholder: { en: "Enter price", fr: "Entrez le prix", ar: "أدخل السعر" },
  add_property_details: { en: "Property Details", fr: "Détails du bien", ar: "تفاصيل العقار" },
  add_property_bedrooms_label: { en: "Bedrooms", fr: "Chambres", ar: "غرف النوم" },
  add_property_bathrooms_label: { en: "Bathrooms", fr: "Salles de bain", ar: "دورات المياه" },
  add_property_area_label: { en: "Area (m²)", fr: "Surface (m²)", ar: "المساحة (م²)" },
  add_property_area_placeholder: { en: "Enter area", fr: "Entrez la surface", ar: "أدخل المساحة بالمتر المربع" },
  add_property_location: { en: "Location", fr: "Localisation", ar: "الموقع الجغرافي" },
  add_property_address_label: { en: "Address", fr: "Adresse", ar: "العنوان" },
  add_property_address_placeholder: { en: "Street address", fr: "Adresse de la rue", ar: "اسم الشارع أو المنطقة" },
  add_property_city_label: { en: "City", fr: "Ville", ar: "المدينة" },
  add_property_city_placeholder: { en: "e.g., Abidjan", fr: "ex: Abidjan", ar: "مثال: أبيدجان" },
  add_property_district_label: { en: "District", fr: "Quartier", ar: "الحي" },
  add_property_district_placeholder: { en: "e.g., Cocody", fr: "ex: Cocody", ar: "مثال: كوكودي أو بلاتو" },
  add_property_features_label: { en: "Features", fr: "Caractéristiques", ar: "المميزات والمرافق" },
  add_property_features_placeholder: { en: "Add a feature (e.g., Swimming Pool)", fr: "Ajouter une caractéristique (ex: Piscine)", ar: "أضف ميزة (مثل: مسبح، حديقة، مرآب)" },
  add_property_add_feature: { en: "Add Feature", fr: "Ajouter", ar: "إضافة ميزة" },
  add_property_contact: { en: "Contact Information", fr: "Informations de contact", ar: "معلومات الاتصال" },
  add_property_name_label: { en: "Your Name", fr: "Votre nom", ar: "اسمك الكامل" },
  add_property_name_placeholder: { en: "Enter your name", fr: "Entrez votre nom", ar: "أدخل اسمك" },
  add_property_phone_label: { en: "Phone Number", fr: "Numéro de téléphone", ar: "رقم الهاتف" },
  add_property_phone_placeholder: { en: "Enter phone number", fr: "Entrez le numéro de téléphone", ar: "أدخل رقم الهاتف مع رمز الدولة" },
  add_property_submit: { en: "Submit Property", fr: "Publier le bien", ar: "نشر العقار الآن" },
  add_property_success: { en: "Property listed successfully!", fr: "Bien publié avec succès!", ar: "تم إرسال العقار بنجاح!" },
  add_property_error: { en: "Please fill all required fields", fr: "Veuillez remplir tous les champs requis", ar: "يرجى ملء جميع الحقول الإلزامية المطلوبة" },
  add_property_cta: { en: "List your property to sell or rent", fr: "Publiez votre bien à vendre ou à louer", ar: "انشر عقارك للبيع أو الإيجار ووصول لآلاف العملاء" },
  add_property_media: { en: "Photos & Media", fr: "Photos & Médias", ar: "الصور والوسائط" },
  add_property_photos_label: { en: "Property Photos (3 required)", fr: "Photos du bien (3 requises)", ar: "صور العقار (3 صور على الأقل مطلوبة)" },
  add_property_video_label: { en: "Property Video (optional)", fr: "Vidéo du bien (optionnel)", ar: "فيديو توضيحي للعقار (اختياري)" },
  add_property_document_label: { en: "Property Document (required)", fr: "Document du bien (requis)", ar: "مستند أو صك الملكية (إلزامي للتوثيق)" },
  add_property_add_photo: { en: "Add Photo", fr: "Ajouter une photo", ar: "إضافة صورة" },
  add_property_add_video: { en: "Add Video", fr: "Ajouter une vidéo", ar: "إضافة فيديو" },
  add_property_add_document: { en: "Add Document", fr: "Ajouter un document", ar: "إرفاق مستند" },
  add_property_payment: { en: "Payment", fr: "Paiement", ar: "رسوم النشر والتحقق" },
  add_property_payment_desc: { en: "Pay 10,000 XOF to list your property", fr: "Payez 10 000 XOF pour publier votre bien", ar: "سداد 10,000 فرنك سيفا لتوثيق ونشر العقار" },
  add_property_select_payment: { en: "Select Payment Method", fr: "Sélectionner le mode de paiement", ar: "اختر طريقة الدفع" },
  add_property_proceed_payment: { en: "Proceed to Payment", fr: "Procéder au paiement", ar: "متابعة الدفع" },
  add_property_payment_success: { en: "Payment successful! Your property is now listed.", fr: "Paiement réussi! Votre bien est maintenant publié.", ar: "تم الدفع بنجاح! تم نشر عقارك." },
  add_property_payment_error: { en: "Payment failed. Please try again.", fr: "Échec du paiement. Veuillez réessayer.", ar: "فشلت عملية الدفع. يرجى المحاولة مرة أخرى." },
  add_property_media_error: { en: "Please add 3 photos and property document", fr: "Veuillez ajouter 3 photos et le document du bien", ar: "يرجى إضافة 3 صور ومستند العقار على الأقل" },
  add_property_payment_required: { en: "Please select a payment method", fr: "Veuillez sélectionner un mode de paiement", ar: "يرجى تحديد وسيلة الدفع للمتابعة" },
  greeting_morning: { en: "Good morning", fr: "Bonjour", ar: "صباح الخير" },
  greeting_afternoon: { en: "Good afternoon", fr: "Bon après-midi", ar: "طاب مساؤك" },
  greeting_evening: { en: "Good evening", fr: "Bonsoir", ar: "مساء الخير" },
  search_map_view: { en: "Map View", fr: "Vue carte", ar: "عرض الخريطة" },
  search_list_view: { en: "List View", fr: "Vue liste", ar: "عرض القائمة" },
  search_close: { en: "Close", fr: "Fermer", ar: "إغلاق" },
  use_my_location: { en: "Use My Location", fr: "Utiliser ma position", ar: "استخدام موقعي الحالي" },
  location_permission_denied: { en: "Permission Denied", fr: "Permission refusée", ar: "تم رفض إذن تحديد الموقع" },
  location_permission_message: { en: "Please enable location services in your device settings to use this feature.", fr: "Veuillez activer les services de localisation dans les paramètres de votre appareil pour utiliser cette fonctionnalité.", ar: "يرجى تفعيل خدمات الموقع من إعدادات جهازك لاستخدام هذه الميزة." },
  location_success: { en: "Success", fr: "Succès", ar: "تم التحديد بنجاح" },
  location_success_message: { en: "Your location has been detected and filled in.", fr: "Votre position a été détectée et remplie.", ar: "تم تحديد موقعك الجغرافي وتعبئته تلقائياً." },
  location_geocode_failed: { en: "Geocoding Failed", fr: "Échec du géocodage", ar: "تعذر تحديد العنوان" },
  location_geocode_failed_message: { en: "Unable to determine your address. Please enter it manually.", fr: "Impossible de déterminer votre adresse. Veuillez la saisir manuellement.", ar: "تعذر تحديد العنوان بدقة. يرجى إدخاله يدوياً." },
  location_error: { en: "Error", fr: "Erreur", ar: "خطأ في الموقع" },
  location_error_message: { en: "Failed to get your location. Please try again or enter manually.", fr: "Échec de l'obtention de votre position. Veuillez réessayer ou saisir manuellement.", ar: "تعذر الحصول على موقعك. يرجى إدخاله يدوياً." },
  dashboard_pending_submissions_title: { en: "Pending Submissions", fr: "Soumissions en attente", ar: "طلبات النشر قيد المراجعة" },
  dashboard_properties_to_verify: { en: "properties to verify", fr: "propriétés à vérifier", ar: "عقارات بانتظار التدقيق والتحقق" },
  dashboard_no_pending: { en: "No pending submissions", fr: "Aucune soumission en attente", ar: "لا توجد طلبات معلقة حالياً" },
  status_pending: { en: "Pending", fr: "En attente", ar: "قيد المراجعة" },
  media_photos: { en: "photos", fr: "photos", ar: "صور" },
  media_video: { en: "Video", fr: "Vidéo", ar: "فيديو" },
  media_document: { en: "Document", fr: "Document", ar: "مستند" },
  payment_label: { en: "Payment:", fr: "Paiement:", ar: "المدفوعات:" },
  action_approve: { en: "Approve", fr: "Approuver", ar: "اعتماد / قبول" },
  action_reject: { en: "Reject", fr: "Rejeter", ar: "رفض" },
  reject_reason_invalid_doc: { en: "Invalid document", fr: "Document invalide", ar: "المستند المرفق غير صالح أو غير مقروء" },
  stat_active_listings: { en: "Active Listings", fr: "Annonces actives", ar: "العقارات النشطة" },
  stat_total_views: { en: "Total Views", fr: "Vues totales", ar: "إجمالي المشاهدات" },
  stat_favorites: { en: "Favorites", fr: "Favoris", ar: "مرات التفضيل" },
  stat_conversion_rate: { en: "Conversion Rate", fr: "Taux de conversion", ar: "معدل التحويل" },
  action_add: { en: "Add", fr: "Ajouter", ar: "إضافة" },
  dashboard_no_active_listings: { en: "No active listings", fr: "Aucune annonce active", ar: "لا توجد عقارات نشطة حالياً" },
  dashboard_add_property_button: { en: "Add Property", fr: "Ajouter une propriété", ar: "إضافة عقار جديد" },
  dashboard_saved_properties: { en: "saved properties", fr: "propriétés sauvegardées", ar: "عقارات محفوظة" },
  action_explore_properties: { en: "Explore Properties", fr: "Explorer les propriétés", ar: "استكشاف العقارات" },
  dashboard_applications_title: { en: "My Applications", fr: "Mes candidatures", ar: "طلباتي وملفاتي" },
  dashboard_applications_subtitle: { en: "Track your rental applications", fr: "Suivi de vos dossiers de location", ar: "متابعة طلبات الإيجار والشراء المقدمة" },
  dashboard_no_applications: { en: "No active applications", fr: "Aucune candidature en cours", ar: "لا توجد طلبات نشطة حالياً" },
  dashboard_applications_empty_hint: { en: "Contact a landlord to apply", fr: "Contactez un propriétaire pour déposer un dossier", ar: "تواصل مع المالك أو الوكيل لتقديم طلبك" },
  role_landlord_verified: { en: "Verified Landlord", fr: "Propriétaire Vérifié", ar: "مالك عقار معتمد" },
  role_tenant: { en: "Tenant", fr: "Locataire", ar: "مستأجر / مشتري" },
  profile_stat_listings: { en: "Listings", fr: "Annonces", ar: "العقارات" },
  profile_stat_views: { en: "Views", fr: "Vues", ar: "المشاهدات" },
  profile_stat_applications: { en: "Applications", fr: "Dossiers", ar: "الطلبات" },
  settings_personal_info: { en: "Personal Information", fr: "Informations personnelles", ar: "المعلومات الشخصية" },
  settings_edit_profile_subtitle: { en: "Edit your profile", fr: "Modifier votre profil", ar: "تعديل بيانات الحساب والملف الشخصي" },
  settings_preferences: { en: "Preferences", fr: "Préférences", ar: "التفضيلات" },
  settings_lang_notif: { en: "Language, notifications", fr: "Langue, notifications", ar: "اللغة، الإشعارات، المظهر" },
  settings_logout_subtitle: { en: "Log out of your account", fr: "Se déconnecter du compte", ar: "تسجيل الخروج من الحساب بأمان" },
  dashboard_title: { en: "ImmoCI Dashboard", fr: "ImmoCI Dashboard", ar: "لوحة تحكم ImmoCI" },
  dashboard_admin_panel: { en: "Admin Panel", fr: "Admin Panel", ar: "بوابة الإدارة" },
  dashboard_back_to_site: { en: "← Back to site", fr: "← Retour au site", ar: "← العودة للموقع" },
  dashboard_subtitle_landlord: { en: "Manage your property listings", fr: "Gérez vos annonces immobilières", ar: "إدارة إعلاناتك العقارية ومتابعة أدائها" },
  dashboard_subtitle_tenant: { en: "Find your favorite properties", fr: "Retrouvez vos coups de cœur", ar: "استعرض عقاراتك المفضلة وطلباتك" },
  role_tenant_space: { en: "Tenant Space", fr: "Espace Locataire", ar: "مساحة العميل" },
  role_landlord_space: { en: "Landlord Space", fr: "Espace Propriétaire", ar: "مساحة المالك / الوكيل" },
  tab_pending: { en: "Pending", fr: "En attente", ar: "قيد المراجعة" },
  tab_applications: { en: "Applications", fr: "Candidatures", ar: "الطلبات" },
  add_property_transaction_id: { en: "Transaction ID", fr: "ID de transaction", ar: "رقم المعاملة (Transaction ID)" },
  add_property_transaction_id_placeholder: { en: "Enter transaction ID", fr: "Entrez l'ID de transaction", ar: "أدخل رقم المعاملة البنكية أو المحفظة" },
  add_property_use_my_location: { en: "Use My Location", fr: "Utiliser ma position", ar: "استخدام موقعي الجغرافي" },
  add_property_video_added: { en: "Video added", fr: "Vidéo ajoutée", ar: "تمت إضافة الفيديو بنجاح" },
  add_property_document_added: { en: "Document added", fr: "Document ajouté", ar: "تم إرفاق المستند بنجاح" },
  add_property_skip_dev: { en: "Skip (Dev)", fr: "Passer (Dev)", ar: "تخطي (بيئة التطوير)" },
  add_property_select_city: { en: "Select City", fr: "Sélectionner une ville", ar: "اختر المدينة" },
  add_property_select_district: { en: "Select District", fr: "Sélectionner un quartier", ar: "اختر الحي" },
  add_property_dev_success: { en: "Dev property submitted successfully", fr: "Bien de test publié avec succès", ar: "تم إرسال العقار التجريبي بنجاح" },
  add_property_dev_error: { en: "Failed to submit dev property", fr: "Échec de la publication du bien de test", ar: "فشل إرسال العقار التجريبي" },
  admin_nav_dashboard: { en: "Dashboard", fr: "Tableau de bord", ar: "لوحة التحكم" },
  admin_nav_analytics: { en: "Analytics", fr: "Analytique", ar: "التحليلات والمؤشرات" },
  admin_nav_properties: { en: "Properties", fr: "Propriétés", ar: "إدارة العقارات" },
  admin_nav_documents: { en: "Documents", fr: "Documents", ar: "مراجعة المستندات" },
  admin_nav_users: { en: "Users", fr: "Utilisateurs", ar: "العملاء والمستخدمون" },
  admin_nav_staff: { en: "Staff", fr: "Personnel", ar: "فريق العمل والصلحيات" },
  admin_nav_support: { en: "Live Chat", fr: "Chat en direct", ar: "المحادثات المباشرة" },
  admin_nav_reports: { en: "Reports", fr: "Rapports", ar: "التقارير المالية" },
  admin_nav_integrations: { en: "Integrations", fr: "Intégrations", ar: "التكامل التقني" },
  admin_nav_settings: { en: "Settings", fr: "Paramètres", ar: "إعدادات المنصة" },
  admin_main_menu: { en: "MAIN MENU", fr: "MENU PRINCIPAL", ar: "القائمة الرئيسية" },
  admin_management: { en: "MANAGEMENT", fr: "GESTION", ar: "الإدارة والرقابة" },
  admin_other: { en: "OTHER", fr: "AUTRE", ar: "أخرى" },
  admin_back_to_app: { en: "Back to App", fr: "Retour à l'application", ar: "العودة للموقع" },
  admin_search_placeholder: { en: "Search admin...", fr: "Recherche admin...", ar: "بحث في لوحة الإدارة..." },
  admin_super_admin: { en: "Super Admin", fr: "Super Administrateur", ar: "مشرف عام" },
  dash_greeting_morning: { en: "Good morning", fr: "Bonjour", ar: "صباح الخير" },
  dash_greeting_afternoon: { en: "Good afternoon", fr: "Bon après-midi", ar: "طاب مساؤك" },
  dash_greeting_evening: { en: "Good evening", fr: "Bonsoir", ar: "مساء الخير" },
  dash_subtitle: { en: "Here's what's happening with your properties today.", fr: "Voici ce qui se passe avec vos propriétés aujourd'hui.", ar: "إليك ملخص أداء عقاراتك ونشاط السوق اليوم." },
  dash_search_placeholder: { en: "Search anything...", fr: "Rechercher...", ar: "ابحث عن أي شيء في اللوحة..." },
  dash_nav_overview: { en: "Overview", fr: "Vue d'ensemble", ar: "نظرة عامة" },
  dash_nav_listings: { en: "Listings", fr: "Annonces", ar: "العقارات" },
  dash_nav_analytics: { en: "Analytics", fr: "Analytique", ar: "التحليلات" },
  dash_nav_ai_assistant: { en: "AI Assistant", fr: "Assistant IA", ar: "المساعد الذكي" },
  dash_nav_pending: { en: "Pending", fr: "En attente", ar: "قيد المراجعة" },
  dash_nav_favorites: { en: "Favorites", fr: "Favoris", ar: "المفضلة" },
  dash_nav_settings: { en: "Settings", fr: "Paramètres", ar: "الإعدادات" },
  dash_nav_back_site: { en: "Back to site", fr: "Retour au site", ar: "العودة للموقع" },
  dash_kpi_revenue: { en: "Total Revenue", fr: "Revenu total", ar: "إجمالي الإيرادات" },
  dash_kpi_listings: { en: "Active Listings", fr: "Annonces actives", ar: "العقارات النشطة" },
  dash_kpi_views: { en: "Total Views", fr: "Vues totales", ar: "إجمالي المشاهدات" },
  dash_kpi_conversion: { en: "Conversion Rate", fr: "Taux de conversion", ar: "معدل التحويل" },
  dash_kpi_vs_last: { en: "vs last month", fr: "vs mois dernier", ar: "مقارنة بالشهر الماضي" },
  dash_period_today: { en: "Today", fr: "Aujourd'hui", ar: "اليوم" },
  dash_period_7d: { en: "7 Days", fr: "7 Jours", ar: "7 أيام" },
  dash_period_30d: { en: "30 Days", fr: "30 Jours", ar: "30 يوماً" },
  dash_period_90d: { en: "90 Days", fr: "90 Jours", ar: "90 يوماً" },
  dash_chart_title: { en: "Revenue Overview", fr: "Aperçu des revenus", ar: "ملخص الإيرادات والمبيعات" },
  dash_chart_revenue: { en: "Revenue", fr: "Revenus", ar: "الإيرادات" },
  dash_chart_views: { en: "Views", fr: "Vues", ar: "المشاهدات" },
  dash_ai_title: { en: "AI Insights", fr: "Analyses IA", ar: "تحليلات الذكاء الاصطناعي" },
  dash_ai_subtitle: { en: "Powered by ImmoCI Intelligence", fr: "Alimenté par l'intelligence ImmoCI", ar: "مدعوم بمحرك ذكاء ImmoCI" },
  dash_ai_insight_1: { en: "Revenue increased 23.5% compared to last month. Cocody and Plateau districts driving growth.", fr: "Les revenus ont augmenté de 23,5% par rapport au mois dernier. Les quartiers Cocody et Plateau portent la croissance.", ar: "ارتفعت الإيرادات بنسبة 23.5% مقارنة بالشهر السابق مدفوعة بالطلب المرتفع في منطقتي كوكودي والبلاتو." },
  dash_ai_insight_2: { en: "Cocody district shows highest demand — consider premium pricing for new listings.", fr: "Le quartier de Cocody affiche la plus forte demande — envisagez un prix premium pour les nouvelles annonces.", ar: "يسجل حي كوكودي أعلى معدل طلب — يوصى باعتماد أسعار مميزة للعقارات الجديدة." },
  dash_ai_insight_3: { en: "3 listings need photo updates for better conversion rates.", fr: "3 annonces nécessitent une mise à jour des photos pour améliorer les taux de conversion.", ar: "3 عقارات بحاجة لتحديث صورها لرفع معدل التحويل والاهتمام." },
  dash_ai_ask: { en: "Ask AI anything...", fr: "Demandez à l'IA...", ar: "اسأل الذكاء الاصطناعي عن بياناتك..." },
  dash_top_properties: { en: "Top Performing Properties", fr: "Propriétés les plus performantes", ar: "العقارات الأعلى أداءً" },
  dash_col_property: { en: "Property", fr: "Propriété", ar: "العقار" },
  dash_col_views: { en: "Views", fr: "Vues", ar: "المشاهدات" },
  dash_col_favs: { en: "Favorites", fr: "Favoris", ar: "المفضلة" },
  dash_col_rate: { en: "Conv. Rate", fr: "Taux Conv.", ar: "معدل التحويل" },
  dash_col_status: { en: "Status", fr: "Statut", ar: "الحالة" },
  dash_col_action: { en: "Action", fr: "Action", ar: "الإجراء" },
  dash_status_active: { en: "Active", fr: "Actif", ar: "نشط" },
  dash_status_pending: { en: "Pending", fr: "En attente", ar: "قيد المراجعة" },
  dash_status_sold: { en: "Sold", fr: "Vendu", ar: "تم البيع" },
  dash_activity_title: { en: "Recent Activity", fr: "Activité récente", ar: "النشاط الأخير" },
  dash_activity_new_view: { en: "New view on", fr: "Nouvelle vue sur", ar: "مشاهدة جديدة على" },
  dash_activity_new_fav: { en: "Added to favorites:", fr: "Ajouté aux favoris :", ar: "تمت إضافته للمفضلة:" },
  dash_activity_price_change: { en: "Price updated for", fr: "Prix mis à jour pour", ar: "تم تحديث سعر" },
  dash_activity_new_inquiry: { en: "New inquiry for", fr: "Nouvelle demande pour", ar: "طلب استفسار جديد على" },
  dash_theme_dark: { en: "Dark", fr: "Sombre", ar: "داكن" },
  dash_theme_light: { en: "Light", fr: "Clair", ar: "فاتح" },
  dash_lang_en: { en: "EN", fr: "EN", ar: "EN" },
  dash_lang_fr: { en: "FR", fr: "FR", ar: "FR" },
  dash_view_all: { en: "View All", fr: "Voir tout", ar: "عرض الكل" },
  dash_this_week: { en: "this week", fr: "cette semaine", ar: "هذا الأسبوع" },
  auth_gate_badge: { en: "SELLER SPACE", fr: "ESPACE VENDEURS", ar: "بوابة الملاك والوكلاء" },
  auth_gate_title: { en: "Sign in to list a property", fr: "Connectez-vous pour publier une annonce", ar: "سجل الدخول لنشر عقارك" },
  auth_gate_subtitle: { en: "To guarantee the safety and authenticity of listings on ImmoCI, you must sign in or create a verified account before submitting a property.", fr: "Pour garantir la sécurité et l'authenticité des offres sur ImmoCI, vous devez vous connecter ou créer un compte vérifié avant de soumettre un bien.", ar: "لضمان أعلى معايير الأمان وموثوقية العروض على ImmoCI، يرجى تسجيل الدخول أو إنشاء حساب موثق قبل نشر عقارك." },
  auth_benefit_1_title: { en: "#1 Visibility in Ivory Coast", fr: "Visibilité N°1 en Côte d'Ivoire", ar: "الانتشار رقم 1 في ساحل العاج" },
  auth_benefit_1_desc: { en: "Reach thousands of qualified buyers and tenants across Abidjan and all of Côte d'Ivoire.", fr: "Diffusez vos biens auprès de milliers d'acheteurs et locataires actifs à Abidjan et partout en Côte d'Ivoire.", ar: "وصول مباشر لآلاف المشترين والمستأجرين المؤهلين في أبيدجان وجميع أنحاء البلاد." },
  auth_benefit_2_title: { en: "Direct contacts & instant alerts", fr: "Contacts directs & alertes instantanées", ar: "تواصل مباشر وتنبيهات فورية" },
  auth_benefit_2_desc: { en: "Receive buyer inquiries directly through WhatsApp, Phone, and Email with zero hassle.", fr: "Recevez directement les demandes d'acheteurs par WhatsApp, téléphone et email sans commission abusive.", ar: "استقبل اتصالات ورسائل العملاء مباشرة عبر واتساب والهاتف دون وسطاء." },
  auth_benefit_3_title: { en: "Dashboard & autonomous management", fr: "Tableau de bord & gestion autonome", ar: "لوحة تحكم وإدارة ذاتية ذكية" },
  auth_benefit_3_desc: { en: "Update pricing, manage photo galleries, and track listing view analytics in real-time.", fr: "Modifiez vos prix, photos et suivez les statistiques de vos annonces en temps réel.", ar: "عدل الأسعار، أدر معارض الصور، وتابع إحصائيات المشاهدات والاهتمام لحظة بلحظة." },
  auth_gate_login_btn: { en: "Sign In / Create Account", fr: "Se connecter / Créer un compte", ar: "تسجيل الدخول / إنشاء حساب" },
  auth_gate_browse_btn: { en: "Browse Listings", fr: "Explorer les biens", ar: "استكشاف العقارات المعروضة" },
  admin_recent_activity: { en: "Recent Activity", fr: "Activité récente", ar: "النشاط الأخير على المنصة" },
  admin_recent_activity_subtitle: { en: "Latest platform activities", fr: "Dernières activités de la plateforme", ar: "أحدث العمليات والأحداث المسجلة" },
  admin_load_more: { en: "Load more", fr: "Charger plus", ar: "تحميل المزيد" },
  admin_just_now: { en: "Just now", fr: "À l'instant", ar: "الآن" },
  admin_min_ago: { en: "min ago", fr: "min", ar: "دقيقة مضت" },
  admin_hours_ago: { en: "hours ago", fr: "heures", ar: "ساعات مضت" },
  admin_days_ago: { en: "days ago", fr: "jours", ar: "أيام مضت" },
  admin_quick_actions: { en: "Quick Actions", fr: "Actions rapides", ar: "إجراءات سريعة" },
  admin_quick_actions_subtitle: { en: "Manage your platform", fr: "Gérez votre plateforme", ar: "إدارة عمليات المنصة" },
  admin_manage_properties: { en: "Manage Properties", fr: "Gérer les propriétés", ar: "إدارة العقارات" },
  admin_manage_users: { en: "Manage Users", fr: "Gérer les utilisateurs", ar: "إدارة المستخدمين" },
  admin_view_reports: { en: "View Reports", fr: "Voir les rapports", ar: "عرض التقارير" },
  admin_ai_assistant: { en: "AI Insight Assistant", fr: "Assistant d'analyse IA", ar: "مساعد تحليل البيانات الذكي" },
  admin_ai_assistant_desc: { en: "Ask questions about your dashboard data, e.g., \"Which month had the best growth?\" or \"Summarize my revenue trends.\"", fr: "Posez des questions sur vos données, ex: \"Quel mois a eu la meilleure croissance ?\" ou \"Résume les tendances de revenus.\"", ar: "اطرح أي سؤال حول بيانات لوحة التحكم، مثل: \"ما هو الشهر الأكثر نمواً؟\" أو \"لخص لي اتجاهات الإيرادات\"." },
  admin_ai_placeholder: { en: "Ask about your data...", fr: "Posez une question sur vos données...", ar: "اطرح سؤالاً عن أرقامك..." },
  admin_ai_chip_kpis: { en: "Summarize KPIs", fr: "Résumer les KPIs", ar: "ملخص المؤشرات الرئيسية" },
  admin_ai_chip_growth: { en: "User Growth Trend", fr: "Tendance de croissance", ar: "معدل نمو المستخدمين" },
  admin_ai_chip_type: { en: "Popular Property Type", fr: "Type de bien populaire", ar: "نوع العقار الأكثر طلباً" },
  admin_ai_ask_another: { en: "Ask another question", fr: "Poser une autre question", ar: "سؤال آخر" },
  admin_ai_analysis_title: { en: "AI Analysis", fr: "Analyse IA", ar: "التحليل الذكي" },
  admin_ai_insights: { en: "AI Insights", fr: "Analyses IA", ar: "رؤى الذكاء الاصطناعي" },
  admin_ai_insights_sub: { en: "AI-generated platform report", fr: "Rapport généré par l'IA", ar: "تقرير تحليلي مولّد آلياً" },
  admin_ai_generate: { en: "Generate", fr: "Générer", ar: "توليد التحليل" },
  admin_ai_no_report: { en: "No report generated", fr: "Aucun rapport généré", ar: "لم يتم إنشاء تقرير بعد" },
  admin_ai_no_report_sub: { en: "Press \"Generate\" to get an AI analysis of the platform.", fr: "Appuyez sur \"Générer\" pour obtenir une analyse IA de la plateforme.", ar: "انقر على \"توليد التحليل\" للحصول على دراسة فورية لبيانات المنصة." },
  admin_ai_analyzing: { en: "Analyzing platform data...", fr: "Analyse des données en cours...", ar: "جاري تحليل بيانات المنصة..." },
  admin_revenue_analytics: { en: "Revenue Analytics", fr: "Analytique des Revenus", ar: "تحليلات الإيرادات المالية" },
  admin_revenue_trend: { en: "Monthly revenue trend", fr: "Tendance mensuelle des revenus", ar: "اتجاه الإيرادات الشهرية" },
  admin_average: { en: "Average", fr: "Moyenne", ar: "المتوسط" },
  admin_total: { en: "Total", fr: "Total", ar: "الإجمالي" },
  admin_peak: { en: "Peak", fr: "Pic", ar: "الذروة" },
  admin_monthly_growth: { en: "Monthly Growth", fr: "Croissance Mensuelle", ar: "النمو الشهري" },
  admin_monthly_growth_sub: { en: "Properties and users over time", fr: "Évolution des biens et utilisateurs", ar: "تطور أعداد العقارات والمستخدمين" },
  admin_properties_label: { en: "Properties", fr: "Propriétés", ar: "عقارات" },
  admin_users_label: { en: "Users", fr: "Utilisateurs", ar: "مستخدمون" },
  admin_performance_distribution: { en: "Performance Distribution", fr: "Distribution de Performance", ar: "توزيع الأداء" },
  admin_property_distribution: { en: "Property Distribution", fr: "Distribution des Propriétés", ar: "توزيع فئات العقارات" },
  admin_by_property_type: { en: "By property type · Q2 2026", fr: "Par type de bien · T2 2026", ar: "حسب نوع العقار · الربع الثاني 2026" },
  admin_exceptional: { en: "Exceptional", fr: "Exceptionnel", ar: "استثنائي" },
  admin_needs_focus: { en: "Needs Focus", fr: "À optimiser", ar: "يحتاج تركيز" },
  admin_underperforming: { en: "Underperforming", fr: "Sous-performance", ar: "أقل من المتوقع" },
  admin_satisfactory: { en: "Satisfactory", fr: "Satisfaisant", ar: "مرضٍ" },
  admin_outstanding: { en: "Outstanding", fr: "Remarquable", ar: "ممتاز" },
  admin_villas: { en: "Villas", fr: "Villas", ar: "فيلات" },
  admin_land: { en: "Land", fr: "Terrains", ar: "أراضي" },
  admin_commercial: { en: "Commercial", fr: "Commercial", ar: "تجاري" },
  admin_apartments: { en: "Apartments", fr: "Appartements", ar: "شقق" },
  admin_stat_total_properties: { en: "Total Properties", fr: "Total Propriétés", ar: "إجمالي العقارات" },
  admin_stat_active_listings: { en: "Active listings", fr: "Annonces actives", ar: "الإعلانات النشطة" },
  admin_stat_total_users: { en: "Total Users", fr: "Total Utilisateurs", ar: "إجمالي المستخدمين" },
  admin_stat_active_accounts: { en: "Active accounts", fr: "Comptes actifs", ar: "الحسابات النشطة" },
  admin_stat_pending_docs: { en: "Pending Docs", fr: "Docs en attente", ar: "المستندات المعلقة" },
  admin_stat_verification_req: { en: "Verification required", fr: "Vérification requise", ar: "بانتظار التحقق" },
  admin_stat_revenue: { en: "Total Revenue", fr: "Revenus Totaux", ar: "إجمالي الإيرادات" },
  admin_stat_revenue_sub: { en: "Platform Volume (FCFA)", fr: "Volume Plateforme (FCFA)", ar: "حجم المعاملات (FCFA)" },
  admin_search_properties: { en: "Search properties...", fr: "Rechercher des biens...", ar: "البحث في العقارات المعروضة..." },
  admin_filters: { en: "Filters", fr: "Filtres", ar: "عوامل التصفية" },
  admin_add_property: { en: "Add Property", fr: "Ajouter un bien", ar: "إضافة عقار جديد" },
  admin_th_property: { en: "Property", fr: "Propriété", ar: "العقار" },
  admin_th_location: { en: "Location", fr: "Emplacement", ar: "الموقع" },
  admin_th_price: { en: "Price", fr: "Prix", ar: "السعر" },
  admin_th_type: { en: "Type", fr: "Type", ar: "النوع" },
  admin_th_status: { en: "Status", fr: "Statut", ar: "الحالة" },
  admin_th_action: { en: "Action", fr: "Action", ar: "الإجراء" },
  admin_no_properties: { en: "No properties listed yet", fr: "Aucune propriété répertoriée", ar: "لا توجد عقارات معروضة بعد" },
  admin_no_properties_sub: { en: "Properties submitted by users or agents will appear here.", fr: "Les propriétés soumises par les utilisateurs ou agents apparaîtront ici.", ar: "العقارات التي يرسلها الملاك أو الوكلاء ستظهر هنا للمراجعة." },
  admin_all_docs_verified: { en: "All documents verified", fr: "Tous les documents sont vérifiés", ar: "تم تدقيق جميع المستندات" },
  admin_all_docs_verified_sub: { en: "Great job! There are currently no pending documents to review.", fr: "Bravo ! Aucun document en attente de vérification pour le moment.", ar: "رائع! لا توجد مستندات بانتظار المراجعة والتدقيق حالياً." },
  admin_available_reports: { en: "Available Reports", fr: "Rapports Disponibles", ar: "التقارير المتوفرة" },
  admin_staff_management: { en: "Staff Management", fr: "Gestion du Personnel", ar: "إدارة فريق العمل والصلاحيات" },
  admin_staff_management_sub: { en: "Manage team members and authorization roles", fr: "Gérez les membres de l'équipe et leurs autorisations", ar: "إدارة أعضاء الفريق، الأدوار، ومستويات الصلاحيات الدقيقة" },
  admin_add_staff_member: { en: "Add Staff Member", fr: "Ajouter un membre", ar: "إضافة موظف جديد" },
  admin_search_staff: { en: "Search staff members...", fr: "Rechercher du personnel...", ar: "البحث عن موظف بالاسم أو الإيميل..." },
  admin_total_staff: { en: "Total Staff", fr: "Total Personnel", ar: "إجمالي الموظفين" },
  admin_active: { en: "Active", fr: "Actif", ar: "نشط" },
  admin_managers: { en: "Managers", fr: "Managers", ar: "مديرون" },
  admin_agents: { en: "Agents", fr: "Agents", ar: "وكلاء" },
  admin_th_staff_member: { en: "Staff Member", fr: "Membre", ar: "الموظف" },
  admin_th_email: { en: "Email", fr: "Email", ar: "البريد الإلكتروني" },
  admin_th_role: { en: "Role", fr: "Rôle", ar: "الدور الوظيفي" },
  admin_th_department: { en: "Department", fr: "Département", ar: "القسم" },
  admin_th_hire_date: { en: "Hire Date", fr: "Date d'embauche", ar: "تاريخ الانضمام" },
  admin_th_last_active: { en: "Last Active", fr: "Dernière activité", ar: "آخر تواجد" },
  admin_th_actions: { en: "Actions", fr: "Actions", ar: "الإجراءات" },
  admin_analytics_overview: { en: "Analytics & Insights Overview", fr: "Aperçu Analytique & Performances", ar: "نظرة عامة على التحليلات والأداء" },
  admin_analytics_overview_sub: { en: "Deep metrics on revenue, platform engagement, and conversion rates", fr: "Métriques détaillées sur les revenus, l'engagement et la conversion", ar: "مؤشرات دقيقة حول الإيرادات، تفاعل المنصة، ومعدلات الإغلاق" },
  admin_support_desk: { en: "Support & Tickets Desk", fr: "Support & Centre de Tickets", ar: "مركز الدعم والتذاكر المباشرة" },
  admin_support_desk_sub: { en: "Triage live customer questions, dispute escalations, and inquiries", fr: "Gestion des demandes clients, signalements et litiges", ar: "معالجة استفسارات العملاء والنزاعات والطلبات المباشرة" },
  admin_verified: { en: "Verified", fr: "Vérifié", ar: "موثق ومعتمد" },
  dept_all: { en: "All Departments", fr: "Tous les départements", ar: "جميع الأقسام" },
  dept_operations: { en: "Operations & Logistics", fr: "Opérations & Logistique", ar: "العمليات واللوجستيات" },
  dept_legal: { en: "Legal & Compliance", fr: "Juridique & Conformité", ar: "الشؤون القانونية والامتثال" },
  dept_sales: { en: "Sales & Commercial", fr: "Commercial & Ventes", ar: "المبيعات والتسويق" },
  dept_support: { en: "Customer Support", fr: "Support Client", ar: "خدمة العملاء والدعم" },
  dept_finance: { en: "Finance & Billing", fr: "Finance & Facturation", ar: "المالية والفوترة" },
  dept_platform_admin: { en: "Platform Administration", fr: "Administration Plateforme", ar: "إدارة المنصة" },
  dept_marketing: { en: "Marketing & Growth", fr: "Marketing & Croissance", ar: "التسويق والنمو" },
  role_super_admin: { en: "Super Admin", fr: "Super Administrateur", ar: "مشرف عام (داخلي)" },
  role_operations_mgr: { en: "Operations Manager", fr: "Responsable Opérations", ar: "مدير العمليات" },
  role_legal_officer: { en: "Legal Officer", fr: "Chargé Juridique", ar: "مسؤول قانوني وتوثيق" },
  role_sales_agent: { en: "Sales Agent", fr: "Agent Commercial", ar: "وكيل عقاري تجاري" },
  role_support_specialist: { en: "Support Specialist", fr: "Spécialiste Support", ar: "اختصاصي خدمة العملاء" },
  role_finance_officer: { en: "Finance Officer", fr: "Responsable Finance", ar: "مسؤول الحسابات والمالية" },
  admin_switch_role_title: { en: "Switch Department & Access Level", fr: "Changer de Département & Rôle", ar: "تبديل القسم ومستوى الصلاحيات (UAT)" },
  admin_switch_role_sub: { en: "Select an access role to test permissions and workflows across the platform.", fr: "Sélectionnez un rôle pour tester les autorisations et flux de travail.", ar: "اختر دوراً وظيفياً لاختبار الصلاحيات وديناميكية الواجهة." },
  admin_current_access: { en: "Active Access Mode", fr: "Mode d'accès actif", ar: "مستوى الوصول الحالي" },
  admin_permissions_label: { en: "Permissions & Scope", fr: "Autorisations & Portée", ar: "الصلاحيات والنطاق المسموح" },
  admin_unrestricted_access: { en: "Full Platform Access (All Sections)", fr: "Accès complet plateforme (Toutes sections)", ar: "وصول شامل لجميع أقسام المنصة" },
  admin_tickets_title: { en: "Live Helpdesk & User Inquiries", fr: "Assistance & Demandes Utilisateurs", ar: "مكتب المساعدة وطلبات العملاء الحية" },
  admin_reply_placeholder: { en: "Type your official response to customer...", fr: "Tapez votre réponse officielle au client...", ar: "اكتب ردك الرسمي والمفصل للعميل..." },
  admin_send_reply: { en: "Send Reply", fr: "Envoyer la réponse", ar: "إرسال الرد" },
  admin_ai_suggest_reply: { en: "AI Draft Reply", fr: "Rédiger avec l'IA", ar: "صياغة الرد بالذكاء الاصطناعي" },
  admin_ticket_status_open: { en: "Open", fr: "Ouvert", ar: "مفتوحة" },
  admin_ticket_status_in_progress: { en: "In Progress", fr: "En cours", ar: "قيد المعالجة" },
  admin_ticket_status_resolved: { en: "Resolved", fr: "Résolu", ar: "تم الحل بنجاح" },
  admin_report_downloaded: { en: "Report downloaded successfully", fr: "Rapport téléchargé avec succès", ar: "تم تحميل التقرير بنجاح" },
  admin_download: { en: "Download", fr: "Télécharger", ar: "تحميل التقرير" },
  common_save: { en: "Save", fr: "Enregistrer", ar: "حفظ" },
  common_cancel: { en: "Cancel", fr: "Annuler", ar: "إلغاء" },
  common_delete: { en: "Delete", fr: "Supprimer", ar: "حذف" },
  common_edit: { en: "Edit", fr: "Modifier", ar: "تعديل" },
  common_create: { en: "Create", fr: "Créer", ar: "إنشاء" },
  common_confirm: { en: "Confirm", fr: "Confirmer", ar: "تأكيد" },
  common_back: { en: "Back", fr: "Retour", ar: "رجوع" },
  common_next: { en: "Next", fr: "Suivant", ar: "التالي" },
  common_close: { en: "Close", fr: "Fermer", ar: "إغلاق" },
  common_search: { en: "Search", fr: "Rechercher", ar: "بحث" },
  common_filter: { en: "Filter", fr: "Filtrer", ar: "تصفية" },
  common_reset: { en: "Reset", fr: "Réinitialiser", ar: "إعادة ضبط" },
  common_loading: { en: "Loading...", fr: "Chargement en cours...", ar: "جاري التحميل..." },
  common_no_results: { en: "No results found", fr: "Aucun résultat trouvé", ar: "لم يتم العثور على نتائج" },
  common_error: { en: "An error occurred", fr: "Une erreur est survenue", ar: "حدث خطأ ما" },
  common_success: { en: "Operation successful", fr: "Opération réussie", ar: "تمت العملية بنجاح" },
  common_unauthorized: { en: "Access Denied", fr: "Accès Non Autorisé", ar: "وصول غير مصرح به" },
  common_unauthorized_desc: { en: "Your role or current permissions do not allow you to access this section.", fr: "Votre rôle ou vos permissions actuelles ne vous autorisent pas à accéder à cette section.", ar: "دورك الوظيفي أو صلاحياتك الحالية لا تسمح لك بالوصول إلى هذا القسم." },
  common_return_dashboard: { en: "Back to Dashboard", fr: "Retour au Tableau de Bord", ar: "العودة للوحة التحكم" },
  common_export_excel: { en: "Export to Excel (.xlsx)", fr: "Exporter en Excel (.xlsx)", ar: "تصدير إلى إكسيل (.xlsx)" },
  common_yes: { en: "Yes", fr: "Oui", ar: "نعم" },
  common_no: { en: "No", fr: "Non", ar: "لا" },
  audit_page_title: { en: "Audit & Security Trail", fr: "Journal d'Audit & Sécurité", ar: "سجل التدقيق والأمان" },
  audit_page_sub: { en: "Forensic event logging, role changes, and compliance tracking", fr: "Traçabilité légale, modifications de rôles et détection des intrusions", ar: "التوثيق القانوني للأحداث، تغييرات الصلاحيات، ومراقبة أمن المنصة" },
  audit_kpi_total: { en: "Recorded Events", fr: "Événements Enregistrés", ar: "إجمالي الأحداث المسجلة" },
  audit_kpi_staff: { en: "Staff & Role Changes", fr: "Modifications Staff/Rôles", ar: "تعديلات الموظفين والصلاحيات" },
  audit_kpi_properties: { en: "Property Validations", fr: "Vérifications Biens", ar: "تدقيق واعتماد العقارات" },
  audit_kpi_alerts: { en: "Security Violations", fr: "Alertes de Sécurité", ar: "تنبيهات ومخالفات الأمان" },
  audit_search_placeholder: { en: "Search audit events by keyword, actor, target...", fr: "Rechercher par mot-clé, auteur, ressource...", ar: "البحث في سجل التدقيق بالكلمة، الفاعل، الهدف..." },
  audit_filter_all_actions: { en: "All Actions", fr: "Toutes les actions", ar: "جميع الإجراءات" },
  audit_filter_all_severities: { en: "All Severities", fr: "Toutes les sévérités", ar: "جميع مستويات الخطورة" },
  audit_filter_24h: { en: "Last 24 Hours", fr: "Dernières 24h", ar: "آخر 24 ساعة" },
  audit_filter_7d: { en: "Last 7 Days", fr: "7 derniers jours", ar: "آخر 7 أيام" },
  audit_filter_30d: { en: "Last 30 Days", fr: "30 derniers jours", ar: "آخر 30 يوماً" },
  audit_filter_all_time: { en: "All Time", fr: "Tout l'historique", ar: "كامل السجل" },
  audit_col_id: { en: "Event ID", fr: "ID Audit", ar: "معرف الحدث" },
  audit_col_time: { en: "Timestamp", fr: "Date & Heure", ar: "التوقيت" },
  audit_col_action: { en: "Action", fr: "Action", ar: "الإجراء" },
  audit_col_severity: { en: "Severity", fr: "Sévérité", ar: "مستوى الخطورة" },
  audit_col_actor: { en: "Actor", fr: "Auteur", ar: "المنفذ" },
  audit_col_target: { en: "Target Resource", fr: "Cible / Ressource", ar: "المورد المستهدف" },
  audit_col_details: { en: "Metadata Details", fr: "Métadonnées", ar: "تفاصيل البيانات" },
  audit_inspect_title: { en: "Audit Event Inspection", fr: "Inspection Détaillée de l'Événement", ar: "فحص تفاصيل حدث التدقيق" },
  audit_inspect_sub: { en: "Immutable forensic signature & metadata payload", fr: "Signature forensique & métadonnées immuables", ar: "البصمة الجنائية الرقمية والبيانات المعتمدة" },
  audit_toast_exported: { en: "Audit log successfully exported to Excel (.xlsx)", fr: "Journal d'audit exporté avec succès en Excel (.xlsx)", ar: "تم تصدير سجل التدقيق بنجاح بصيغة إكسيل (.xlsx)" },
  reports_page_title: { en: "Reporting & Operational Audit Center", fr: "Centre de Rapports & Audit d'Activité", ar: "مركز التقارير والتدقيق التشغيلي" },
  reports_page_sub: { en: "Live business analytics and certified Excel workbooks based on real database records", fr: "Analyses réelles du portefeuille et exports de données certifiés OpenXML", ar: "تحليلات حقيقية للمحفظة العقارية وتصدير تقارير إكسيل معتمدة" },
  reports_tab_revenue: { en: "Revenue & Volume", fr: "Revenus & Volume", ar: "الإيرادات والمعاملات" },
  reports_tab_inventory: { en: "Property Inventory", fr: "Parc Immobilier", ar: "المخزون العقاري" },
  reports_tab_inquiries: { en: "Inquiries & Leads", fr: "Demandes & Visites", ar: "الطلبات والاستفسارات" },
  reports_tab_customers: { en: "Customers Directory", fr: "Répertoire Clients", ar: "دليل العملاء" },
  reports_tab_staff: { en: "Staff Activity", fr: "Activité Équipe", ar: "نشاط فريق العمل" },
  reports_filter_period: { en: "Period:", fr: "Période :", ar: "الفترة:" },
  reports_filter_commune: { en: "District:", fr: "Commune :", ar: "البلدية/الحي:" },
  reports_filter_type: { en: "Property Type:", fr: "Type de bien :", ar: "نوع العقار:" },
  reports_filter_status: { en: "Status:", fr: "Statut :", ar: "الحالة:" },
  reports_export_btn: { en: "Export Report (.xlsx)", fr: "Télécharger Rapport (.xlsx)", ar: "تنزيل التقرير (.xlsx)" },
  reports_export_locked: { en: "Export Locked (Permission reports.export required)", fr: "Export Verrouillé (Permission requise)", ar: "التصدير مقفل (يتطلب إذن التصدير)" },
  staff_page_title: { en: "Staff & Access Management", fr: "Gestion des Collaborateurs & Habilitations", ar: "إدارة الموظفين والصلاحيات" },
  staff_page_sub: { en: "Manage team directory, roles, and granular security permissions", fr: "Répertoire des collaborateurs, attribution des rôles et contrôle d'accès granulaire", ar: "دليل الموظفين، تحديد الأدوار، وإدارة الصلاحيات الدقيقة" },
  staff_add_member: { en: "New Staff Member", fr: "Nouveau Collaborateur", ar: "موظف جديد" },
  staff_col_name: { en: "Collaborator", fr: "Collaborateur", ar: "الموظف" },
  staff_col_role: { en: "Role", fr: "Rôle", ar: "الدور" },
  staff_col_department: { en: "Department", fr: "Département", ar: "القسم" },
  staff_col_permissions: { en: "Permissions", fr: "Permissions", ar: "الصلاحيات" },
  staff_col_status: { en: "Status", fr: "Statut", ar: "الحالة" },
  staff_col_last_active: { en: "Last Active", fr: "Dernière Activité", ar: "آخر ظهور" },
  staff_edit_permissions: { en: "Edit Access & Permissions", fr: "Gérer les Droits d'Accès", ar: "تعديل الصلاحيات ومستوى الوصول" },
  staff_toast_saved: { en: "Staff permissions updated successfully", fr: "Permissions mises à jour avec succès", ar: "تم تحديث صلاحيات الموظف بنجاح" },
  staff_toast_created: { en: "Staff member added successfully", fr: "Collaborateur ajouté avec succès", ar: "تمت إضافة الموظف الجديد بنجاح" },
  amenity_swimming_pool: { en: "Swimming Pool", fr: "Piscine", ar: "مسبح" },
  amenity_garden: { en: "Garden", fr: "Jardin", ar: "حديقة" },
  amenity_parking: { en: "Parking", fr: "Parking / Garage", ar: "موقف سيارات / مرآب" },
  amenity_security: { en: "24/7 Security", fr: "Sécurité 24/7", ar: "حراسة وأمن 24/7" },
  amenity_air_conditioning: { en: "Air Conditioning", fr: "Climatisation", ar: "تكييف هواء" },
  amenity_furnished: { en: "Furnished", fr: "Meublé", ar: "مفروش بالكامل" },
  amenity_elevator: { en: "Elevator", fr: "Ascenseur", ar: "مصعد" },
  amenity_balcony: { en: "Balcony / Terrace", fr: "Balcon / Terrasse", ar: "شرفة / تراس" },
  amenity_generator: { en: "Backup Generator", fr: "Groupe électrogène", ar: "مولد كهربائي احتياطي" },
  amenity_borehole: { en: "Water Tank / Borehole", fr: "Cuve d'eau / Forage", ar: "خزان مياه / بئر" },
  customer_care_title: { en: "Customer Care", fr: "Service Client", ar: "خدمة العملاء" },
  customer_care_tagline: { en: "Here to help you 7 days a week", fr: "À votre service 7j/7", ar: "في خدمتكم طوال أيام الأسبوع" },
  customer_care_disclaimer: { en: "You are connected with ImmoCI Customer Care", fr: "Vous échangez avec le Service Client ImmoCI", ar: "أنت الآن في محادثة مع خدمة عملاء ImmoCI" },
};

export type TranslationKey = keyof typeof dictionary;

export interface LanguageContextValue {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey | string, fallback?: string) => string;
  isLoaded: boolean;
  isRTL: boolean;
  dir: 'ltr' | 'rtl';
}

export const [LanguageProvider, useLanguage] = createContextHook<LanguageContextValue>(() => {
  const [language, setLanguageState] = useState<LanguageCode>('fr');
  const [isLoaded, setIsLoaded] = useState(false);

  // Synchronize HTML document dir and lang on Web
  useEffect(() => {
    if (Platform.OS === 'web' && typeof document !== 'undefined') {
      document.documentElement.lang = language;
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    }
  }, [language]);

  useEffect(() => {
    let mounted = true;
    const loadLanguage = async () => {
      try {
        const stored = await AsyncStorage.getItem('app_language');
        if (mounted && (stored === 'en' || stored === 'fr' || stored === 'ar')) {
          setLanguageState(stored as LanguageCode);
        }
      } catch (error) {
        console.error('Error loading language:', error);
      } finally {
        if (mounted) {
          setIsLoaded(true);
        }
      }
    };
    loadLanguage();
    return () => {
      mounted = false;
    };
  }, []);

  const setLanguage = useCallback(async (lang: LanguageCode) => {
    setLanguageState(lang); // Optimistic update
    try {
      await AsyncStorage.setItem('app_language', lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  }, []);

  const toggleLanguage = useCallback(() => {
    const cycle: Record<LanguageCode, LanguageCode> = {
      fr: 'en',
      en: 'ar',
      ar: 'fr',
    };
    setLanguage(cycle[language] || 'fr');
  }, [language, setLanguage]);

  const t = useCallback(
    (key: TranslationKey | string, fallback?: string) => {
      const entry = dictionary[key];
      if (entry && entry[language]) {
        return entry[language];
      }
      if (fallback !== undefined) {
        return fallback;
      }
      return String(key);
    },
    [language]
  );

  const isRTL = language === 'ar';
  const dir = isRTL ? ('rtl' as const) : ('ltr' as const);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage,
      t,
      isLoaded,
      isRTL,
      dir,
    }),
    [language, setLanguage, toggleLanguage, t, isLoaded, isRTL, dir]
  );

  return value;
});
